# DO NOT EDIT - GENERATED by scripts/unasync.py
# source of truth: tests/conformance/_async/test_opendal.py
"""Opendal-engine specifics; shared behavior lives in test_backends.py.

Runs offline over the credential-free memory service.
"""

from collections.abc import Iterator
from pathlib import PurePosixPath as P

import pytest

from storix._sync.backends.opendal import OpendalBackend
from storix.models import RawStat


def _astream(*chunks: bytes) -> Iterator[bytes]:
    yield from chunks


def test_list_dir_non_empty_directory_makes_no_stat_calls(
    monkeypatch: pytest.MonkeyPatch,
):
    # list-first: one real child proves the directory; the old stat
    # precheck cost up to two extra requests per listing
    backend = OpendalBackend('memory')
    backend.make_dir(P('/d'), parents=False)
    backend.write_stream(P('/d/a.txt'), _astream(b'x'), mode='w', content_type=None)

    calls = 0
    original = backend.stat

    def counting_stat(path: P) -> RawStat:
        nonlocal calls
        calls += 1
        return original(path)

    monkeypatch.setattr(backend, 'stat', counting_stat)

    entries = list(backend.list_dir(P('/d')))

    assert {entry.name for entry in entries} == {'a.txt'}
    assert calls == 0
