# DO NOT EDIT - GENERATED by scripts/unasync.py
# source of truth: tests/conformance/_async/test_backends.py
# ruff: noqa: A004
"""The backend conformance suite: one behavior spec, every backend.

Every StorageBackend implementation must pass every test here - this is
the enforcement mechanism for 'one behavior everywhere'. Backend-specific
quirks live in the per-backend test files.
"""

import os
import uuid

from collections.abc import Iterator
from pathlib import Path, PurePosixPath as P

import pytest

from storix._sync import Storix
from storix._sync.backends import StorageBackend
from storix._sync.backends.local import LocalBackend
from storix._sync.backends.memory import MemoryBackend
from storix._sync.layers import (
    CacheLayer,
    DataUrlLayer,
    MetadataLayer,
    ObservabilityLayer,
    SandboxLayer,
)
from storix.errors import (
    AlreadyExistsError,
    DirectoryNotEmptyError,
    IsADirectoryError,
    NotADirectoryError,
    PathNotFoundError,
    UnsupportedOperationError,
)
from storix.types import EchoMode


@pytest.fixture(
    params=[
        'memory',
        'local',
        'sandbox',
        'metadata',
        'dataurl',
        'cache',
        'observability',
        'opendal-memory',
        pytest.param('azure', marks=pytest.mark.integration),
        pytest.param('azblob', marks=pytest.mark.integration),
        pytest.param('s3', marks=pytest.mark.integration),
        pytest.param('gcs', marks=pytest.mark.integration),
    ]
)
def backend(  # noqa: PLR0911, PLR0912, PLR0915 - one branch per backend param
    request: pytest.FixtureRequest, tmp_path: Path
) -> Iterator[StorageBackend]:
    if request.param == 'memory':
        yield MemoryBackend()
        return
    if request.param == 'local':
        yield LocalBackend(tmp_path)
        return
    if request.param == 'sandbox':
        # a layer must satisfy the full port contract like any backend
        inner = MemoryBackend()
        inner.make_dir(P('/jail'), parents=False)
        yield SandboxLayer(inner, root='/jail')
        return
    if request.param == 'metadata':
        # sidecar metadata over a backend that lacks it natively; the
        # hidden sidecar must not disturb any listing/du/stat contract
        yield MetadataLayer(LocalBackend(tmp_path))
        return
    if request.param == 'dataurl':
        yield DataUrlLayer(MemoryBackend())
        return
    if request.param == 'cache':
        # the whole conformance suite proves cache eviction is correct:
        # every write-then-read must return fresh data, not a stale hit
        yield CacheLayer(MemoryBackend())
        return
    if request.param == 'observability':
        # no sink set: the layer must be a pure passthrough
        yield ObservabilityLayer(MemoryBackend())
        return
    if request.param == 'opendal-memory':
        # the internal engine over its credential-free memory service:
        # keeps every engine code path in the default (non-integration) run
        from storix._sync.backends.opendal import OpendalBackend

        yield OpendalBackend('memory')
        return
    if request.param == 'azblob':
        container = os.environ.get('STORIX_TEST_AZBLOB_CONTAINER')
        if not container:
            pytest.skip('azblob integration credentials not configured')
        from storix._sync.backends.azblob import AzureBlobBackend

        azblob = AzureBlobBackend(
            container,
            account_name=os.environ['STORIX_TEST_AZBLOB_ACCOUNT_NAME'],
            credential=os.environ.get('STORIX_TEST_AZBLOB_CREDENTIAL'),
            endpoint=os.environ.get('STORIX_TEST_AZBLOB_ENDPOINT'),
            root=f'/storix-conformance-{uuid.uuid4().hex[:12]}',
        )
        try:
            yield azblob
        finally:
            azblob._op.remove_all('/')
        return
    if request.param == 's3':
        bucket = os.environ.get('STORIX_TEST_S3_BUCKET')
        if not bucket:
            pytest.skip('s3 integration credentials not configured')
        from storix._sync.backends.s3 import S3Backend

        s3 = S3Backend(
            bucket,
            region=os.environ.get('STORIX_TEST_S3_REGION', 'us-east-1'),
            access_key_id=os.environ.get('AWS_ACCESS_KEY_ID'),
            secret_access_key=os.environ.get('AWS_SECRET_ACCESS_KEY'),
            endpoint=os.environ.get('STORIX_TEST_S3_ENDPOINT'),
            # a per-run root keeps concurrent runs isolated and cleanup exact
            root=f'/storix-conformance-{uuid.uuid4().hex[:12]}',
        )
        try:
            yield s3
        finally:
            s3._op.remove_all('/')
        return
    if request.param == 'gcs':
        bucket = os.environ.get('STORIX_TEST_GCS_BUCKET')
        if not bucket:
            pytest.skip('gcs integration credentials not configured')
        from storix._sync.backends.gcs import GcsBackend

        gcs = GcsBackend(
            bucket,
            credential_path=os.environ.get('STORIX_TEST_GCS_CREDENTIAL_PATH'),
            endpoint=os.environ.get('STORIX_TEST_GCS_ENDPOINT'),
            root=f'/storix-conformance-{uuid.uuid4().hex[:12]}',
        )
        try:
            yield gcs
        finally:
            gcs._op.remove_all('/')
        return

    account = os.environ.get('STORIX_TEST_AZURE_ACCOUNT_NAME')
    token = os.environ.get('STORIX_TEST_AZURE_CREDENTIAL')
    if not (account and token):
        pytest.skip('azure integration credentials not configured')
    from storix._sync.backends.azure import AzureBackend

    azure = AzureBackend(
        f'storix-conformance-{uuid.uuid4().hex[:12]}',
        account_name=account,
        credential=token,
    )
    azure._filesystem.create_file_system()
    try:
        yield azure
    finally:
        azure._filesystem.delete_file_system()
        azure.close()


def _astream(*chunks: bytes) -> Iterator[bytes]:
    yield from chunks


def put(
    backend: StorageBackend, path: str, data: bytes = b'', mode: EchoMode = 'w'
) -> None:
    backend.write_stream(P(path), _astream(data), mode=mode, content_type=None)


def test_root_exists_initially(backend: StorageBackend):
    assert backend.exists(P('/'))
    assert not backend.exists(P('/anything'))


# --- write / read ---


def test_write_creates_and_read_round_trips(backend: StorageBackend):
    put(backend, '/a.txt', b'hello')
    assert backend.read(P('/a.txt')) == b'hello'


def test_whole_write_creates_and_round_trips(backend: StorageBackend):
    backend.write(P('/a.txt'), b'whole', mode='w', content_type=None)
    assert backend.read(P('/a.txt')) == b'whole'


def test_write_truncates_existing(backend: StorageBackend):
    put(backend, '/a.txt', b'old content')
    put(backend, '/a.txt', b'new')
    assert backend.read(P('/a.txt')) == b'new'


def test_append_extends(backend: StorageBackend):
    put(backend, '/a.txt', b'hello ')
    put(backend, '/a.txt', b'world', mode='a')
    assert backend.read(P('/a.txt')) == b'hello world'


def test_append_creates_missing(backend: StorageBackend):
    put(backend, '/a.txt', b'created', mode='a')
    assert backend.read(P('/a.txt')) == b'created'


@pytest.mark.parametrize('mode', ['w', 'a'])
def test_write_onto_directory_raises(backend: StorageBackend, mode: EchoMode):
    backend.make_dir(P('/d'), parents=False)
    with pytest.raises(IsADirectoryError):
        put(backend, '/d', b'x', mode=mode)


def test_read_missing_raises(backend: StorageBackend):
    with pytest.raises(PathNotFoundError):
        backend.read(P('/nope'))


def test_read_directory_raises(backend: StorageBackend):
    backend.make_dir(P('/d'), parents=False)
    with pytest.raises(IsADirectoryError):
        backend.read(P('/d'))


def test_read_stream_yields_content(backend: StorageBackend):
    put(backend, '/a.txt', b'streamed')
    chunks = list(backend.read_stream(P('/a.txt')))
    assert b''.join(chunks) == b'streamed'


def test_read_stream_honors_chunk_size(backend: StorageBackend):
    put(backend, '/a.txt', b'0123456789')
    chunks = list(backend.read_stream(P('/a.txt'), chunk_size=4))
    assert b''.join(chunks) == b'0123456789'
    assert all(0 < len(chunk) <= 4 for chunk in chunks)


@pytest.mark.parametrize('chunk_size', [0, -1])
def test_read_stream_rejects_non_positive_chunk_size(
    backend: StorageBackend, chunk_size: int
):
    put(backend, '/a.txt', b'x')
    with pytest.raises(ValueError, match='chunk_size must be positive'):
        list(backend.read_stream(P('/a.txt'), chunk_size=chunk_size))


@pytest.mark.parametrize('chunk_size', [0, -1])
def test_write_stream_rejects_non_positive_chunk_size(
    backend: StorageBackend, chunk_size: int
):
    with pytest.raises(ValueError, match='chunk_size must be positive'):
        backend.write_stream(
            P('/a.txt'),
            _astream(b'x'),
            chunk_size=chunk_size,
            mode='w',
            content_type=None,
        )
    assert not backend.exists(P('/a.txt'))


# --- list_dir ---


def test_list_dir_entries(backend: StorageBackend):
    backend.make_dir(P('/d'), parents=False)
    backend.make_dir(P('/d/sub'), parents=False)
    put(backend, '/d/a.txt', b'12345')

    entries = {(e.name, e.is_dir, e.size) for e in backend.list_dir(P('/d'))}
    # directory entries report size=None: a listing size is only meaningful
    # for files, and du() recurses into directories regardless
    assert entries == {('sub', True, None), ('a.txt', False, 5)}


def test_list_dir_on_file_raises(backend: StorageBackend):
    put(backend, '/a.txt')
    with pytest.raises(NotADirectoryError):
        for _ in backend.list_dir(P('/a.txt')):
            pass


def test_list_dir_missing_raises(backend: StorageBackend):
    with pytest.raises(PathNotFoundError):
        for _ in backend.list_dir(P('/nope')):
            pass


def test_list_dir_empty_directory_yields_nothing(backend: StorageBackend):
    backend.make_dir(P('/d'), parents=False)
    assert list(backend.list_dir(P('/d'))) == []


def test_list_dir_tolerates_delete_during_iteration(backend: StorageBackend):
    backend.make_dir(P('/d'), parents=False)
    for name in ('a', 'b', 'c'):
        put(backend, f'/d/{name}')

    for entry in backend.list_dir(P('/d')):
        backend.delete(P('/d') / entry.name)

    assert list(backend.list_dir(P('/d'))) == []


# --- list_tree (bulk_listing) ---


def test_list_tree_yields_every_descendant_file(backend: StorageBackend):
    if not backend.capabilities.bulk_listing:
        pytest.skip('backend does not advertise bulk_listing')
    backend.make_dir(P('/d'), parents=False)
    backend.make_dir(P('/d/sub'), parents=False)
    put(backend, '/d/a.txt')
    put(backend, '/d/sub/b.txt')

    descendants = {str(p) for p in backend.list_tree(P('/d'))}
    # every file at any depth appears; directory markers may or may not,
    # and the directory itself never does
    assert {'/d/a.txt', '/d/sub/b.txt'} <= descendants
    assert '/d' not in descendants


def test_list_tree_on_empty_dir_yields_nothing(backend: StorageBackend):
    if not backend.capabilities.bulk_listing:
        pytest.skip('backend does not advertise bulk_listing')
    backend.make_dir(P('/empty'), parents=False)
    assert list(backend.list_tree(P('/empty'))) == []


def test_list_tree_on_file_raises(backend: StorageBackend):
    if not backend.capabilities.bulk_listing:
        pytest.skip('backend does not advertise bulk_listing')
    put(backend, '/a.txt')
    with pytest.raises(NotADirectoryError):
        for _ in backend.list_tree(P('/a.txt')):
            pass


# --- stat ---


def test_stat_file(backend: StorageBackend):
    put(backend, '/a.txt', b'12345')
    props = backend.stat(P('/a.txt'))
    assert props.kind == 'file'
    assert props.size == 5
    assert props.created.tzinfo is not None
    assert props.modified.tzinfo is not None


def test_stat_directory_size_is_zero(backend: StorageBackend):
    backend.make_dir(P('/d'), parents=False)
    put(backend, '/d/a.txt', b'12345')
    props = backend.stat(P('/d'))
    assert props.kind == 'directory'
    assert props.size == 0


def test_metadata_round_trip(backend: StorageBackend):
    if not backend.capabilities.custom_metadata:
        pytest.skip('backend does not advertise custom_metadata')
    backend.write_stream(
        P('/m.txt'),
        _astream(b'x'),
        mode='w',
        content_type=None,
        metadata={'owner': 'tests'},
    )
    raw = backend.stat(P('/m.txt'))
    assert raw.metadata == {'owner': 'tests'}


def test_metadata_absent_by_default(backend: StorageBackend):
    put(backend, '/plain.txt', b'x')
    assert (backend.stat(P('/plain.txt'))).metadata is None


def test_metadata_replace_semantics(backend: StorageBackend):
    """Provided mapping replaces; None preserves on append; {} clears."""
    if not backend.capabilities.custom_metadata:
        pytest.skip('backend does not advertise custom_metadata')

    def put_meta(data: bytes, mode: EchoMode, metadata: dict | None) -> None:
        backend.write_stream(
            P('/m.txt'), _astream(data), mode=mode, content_type=None, metadata=metadata
        )

    def meta() -> dict | None:
        raw = backend.stat(P('/m.txt'))
        return dict(raw.metadata) if raw.metadata is not None else None

    put_meta(b'x', 'w', {'a': '1', 'b': '2'})
    put_meta(b'y', 'a', None)  # None preserves on append
    assert meta() == {'a': '1', 'b': '2'}

    put_meta(b'z', 'a', {'c': '3'})  # replace, not merge
    assert meta() == {'c': '3'}

    put_meta(b'w', 'a', {})  # empty mapping clears
    assert meta() is None


def test_set_metadata_replaces_without_touching_content(
    backend: StorageBackend,
):
    if not backend.capabilities.custom_metadata:
        with pytest.raises(UnsupportedOperationError):
            backend.set_metadata(P('/x'), {'a': '1'})
        return

    put(backend, '/m.txt', b'content')
    backend.set_metadata(P('/m.txt'), {'a': '1'})
    assert (backend.stat(P('/m.txt'))).metadata == {'a': '1'}
    assert backend.read(P('/m.txt')) == b'content'

    backend.set_metadata(P('/m.txt'), {})  # empty mapping clears
    assert (backend.stat(P('/m.txt'))).metadata is None


def test_set_metadata_on_directory_raises(backend: StorageBackend):
    if not backend.capabilities.custom_metadata:
        pytest.skip('backend does not advertise custom_metadata')
    backend.make_dir(P('/d'), parents=False)
    with pytest.raises(IsADirectoryError):
        backend.set_metadata(P('/d'), {'a': '1'})


def test_make_url_respects_capability(backend: StorageBackend):
    put(backend, '/u.txt', b'x')
    if backend.capabilities.presigned_urls:
        url = backend.make_url(P('/u.txt'), expires_in=60)
        # the contract is 'a URL string' - scheme is provider-specific
        # (https for SAS, data: for the data-url layer)
        assert ('://' in url) or url.startswith('data:')
    else:
        with pytest.raises(UnsupportedOperationError):
            backend.make_url(P('/u.txt'), expires_in=60)


def test_append_updates_modified(backend: StorageBackend):
    put(backend, '/a.txt', b'x')
    before = backend.stat(P('/a.txt'))
    put(backend, '/a.txt', b'y', mode='a')
    after = backend.stat(P('/a.txt'))
    assert after.modified >= before.modified


# --- make_dir ---


def test_make_dir_plain(backend: StorageBackend):
    backend.make_dir(P('/d'), parents=False)
    assert (backend.stat(P('/d'))).kind == 'directory'


def test_make_dir_missing_parent_raises(backend: StorageBackend):
    with pytest.raises(PathNotFoundError) as excinfo:
        backend.make_dir(P('/missing/d'), parents=False)
    assert str(excinfo.value.path) == '/missing'


def test_make_dir_parent_is_file_raises(backend: StorageBackend):
    put(backend, '/a.txt')
    with pytest.raises(NotADirectoryError):
        backend.make_dir(P('/a.txt/d'), parents=False)


def test_make_dir_existing_raises(backend: StorageBackend):
    backend.make_dir(P('/d'), parents=False)
    with pytest.raises(AlreadyExistsError):
        backend.make_dir(P('/d'), parents=False)


def test_make_dir_parents_creates_chain(backend: StorageBackend):
    backend.make_dir(P('/a/b/c'), parents=True)
    for path in ('/a', '/a/b', '/a/b/c'):
        assert (backend.stat(P(path))).kind == 'directory'


def test_make_dir_parents_is_idempotent(backend: StorageBackend):
    backend.make_dir(P('/d'), parents=True)
    backend.make_dir(P('/d'), parents=True)  # no raise


def test_make_dir_parents_existing_file_still_raises(backend: StorageBackend):
    put(backend, '/a.txt')
    with pytest.raises(AlreadyExistsError):
        backend.make_dir(P('/a.txt'), parents=True)


# --- delete ---


def test_delete_file(backend: StorageBackend):
    put(backend, '/a.txt')
    backend.delete(P('/a.txt'))
    assert not backend.exists(P('/a.txt'))


def test_delete_empty_directory(backend: StorageBackend):
    backend.make_dir(P('/d'), parents=False)
    backend.delete(P('/d'))
    assert not backend.exists(P('/d'))


def test_delete_non_empty_directory_raises(backend: StorageBackend):
    backend.make_dir(P('/d'), parents=False)
    put(backend, '/d/a.txt')
    with pytest.raises(DirectoryNotEmptyError):
        backend.delete(P('/d'))


def test_delete_missing_raises(backend: StorageBackend):
    with pytest.raises(PathNotFoundError):
        backend.delete(P('/nope'))


# --- generic fallbacks / native fast paths through the same contract ---


def test_du_file(backend: StorageBackend):
    put(backend, '/a.txt', b'12345')
    assert backend.du(P('/a.txt')) == 5


def test_du_sums_tree(backend: StorageBackend):
    backend.make_dir(P('/a/b'), parents=True)
    put(backend, '/a/f1', b'123')
    put(backend, '/a/b/f2', b'12345')
    assert backend.du(P('/a')) == 8
    assert backend.du(P('/')) == 8


def test_move_file(backend: StorageBackend):
    put(backend, '/src.txt', b'payload')
    backend.move(P('/src.txt'), P('/dst.txt'))
    assert backend.read(P('/dst.txt')) == b'payload'
    assert not backend.exists(P('/src.txt'))


def test_move_directory_tree(backend: StorageBackend):
    backend.make_dir(P('/d/sub'), parents=True)
    put(backend, '/d/sub/a.txt', b'x')
    backend.move(P('/d'), P('/renamed'))
    assert backend.read(P('/renamed/sub/a.txt')) == b'x'
    assert not backend.exists(P('/d'))


def test_copy_file_is_independent(backend: StorageBackend):
    put(backend, '/src.txt', b'payload')
    backend.copy(P('/src.txt'), P('/dst.txt'))
    assert backend.read(P('/dst.txt')) == b'payload'

    # mutating the copy must not touch the original (no buffer aliasing)
    put(backend, '/dst.txt', b' more', mode='a')
    assert backend.read(P('/src.txt')) == b'payload'


def test_delete_tree_removes_everything(backend: StorageBackend):
    backend.make_dir(P('/d/sub'), parents=True)
    put(backend, '/d/a.txt', b'x')
    put(backend, '/d/sub/b.txt', b'y')

    backend.delete_tree(P('/d'))

    for path in ('/d', '/d/sub', '/d/a.txt', '/d/sub/b.txt'):
        assert not backend.exists(P(path))
    assert backend.exists(P('/'))


# --- concurrent fan-out (the sync twin runs these through the thread pool) ---


def test_fan_out_read_round_trips(backend: StorageBackend):
    """A multi-target read fan-out returns every target's content, in order.

    Runs on every backend in both flavors; the generated sync twin drives
    the ``concurrent`` thread pool over distinct keys, which is the
    thread-safety check the ADR calls for.
    """
    fs = Storix(backend)
    names = [f'/f{i}.txt' for i in range(10)]
    for i, name in enumerate(names):
        fs.echo(f'content-{i}'.encode(), name)

    joined = fs.cat(*names)

    assert joined == b''.join(f'content-{i}'.encode() for i in range(10))


# --- provisioning (control-plane; capability-gated) ---


def test_local_provision_ensures_base_and_reports_present(tmp_path: Path):
    # Given a local backend anchored at a base created in the constructor
    root = tmp_path / 'store'
    backend = LocalBackend(root)
    # Then it advertises the capability the core gate consults
    assert backend.capabilities.provisioning is True
    # When provision runs
    created = backend.provision()
    # Then it reports the root already present and the base still exists
    assert created is False
    assert root.is_dir()
