# DO NOT EDIT - GENERATED by scripts/unasync.py
# source of truth: tests/_async/test_factory.py
from pathlib import Path, PurePosixPath

import pytest

from storix._sync import Storix, get_storage
from storix._sync.backends.local import LocalBackend
from storix._sync.backends.memory import MemoryBackend
from storix.errors import ConfigurationError, StorageError


def test_default_is_local(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    monkeypatch.setenv('STORIX_LOCAL_BASE', str(tmp_path))
    fs = get_storage()
    assert isinstance(fs, Storix)
    assert isinstance(fs.backend, LocalBackend)
    assert fs.backend._base == tmp_path


def test_provider_argument_overrides_env(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    monkeypatch.setenv('STORIX_PROVIDER', 'azure')
    fs = get_storage('local', base=str(tmp_path))
    assert isinstance(fs.backend, LocalBackend)


def test_kwargs_override_env(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    monkeypatch.setenv('STORIX_LOCAL_BASE', '/definitely/not/this')
    fs = get_storage('local', base=str(tmp_path))
    assert fs.backend._base == tmp_path


def test_env_selects_provider(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    monkeypatch.setenv('STORIX_PROVIDER', 'local')
    monkeypatch.setenv('STORIX_LOCAL_BASE', str(tmp_path))
    assert isinstance(get_storage().backend, LocalBackend)


def test_memory_provider_builds_zero_config():
    assert isinstance(get_storage('memory').backend, MemoryBackend)


def test_env_selects_memory_provider(monkeypatch: pytest.MonkeyPatch):
    monkeypatch.setenv('STORIX_PROVIDER', 'memory')
    assert isinstance(get_storage().backend, MemoryBackend)


def test_memory_provider_rejects_configuration_overrides():
    with pytest.raises(ConfigurationError, match='accepts no configuration'):
        get_storage('memory', unexpected=True)


def test_azure_from_kwargs_builds_without_network():
    fs = get_storage('azure', container='raw', account_name='acct', credential='token')
    assert fs.backend.container == 'raw'


def test_azure_transfer_overrides_reach_backend_and_sdk():
    fs = get_storage(
        'azure',
        container='raw',
        account_name='acct',
        credential='token',
        read_chunk_size=1_234,
        write_chunk_size=5_678,
        read_prefetch_size=9_012,
    )
    backend = fs.backend
    assert backend.default_read_chunk_size == 1_234
    assert backend.default_write_chunk_size == 5_678
    assert backend._service._config.max_chunk_get_size == 1_234
    assert backend._service._config.max_single_get_size == 9_012


@pytest.mark.parametrize(
    'field', ['read_chunk_size', 'write_chunk_size', 'read_prefetch_size']
)
def test_azure_transfer_overrides_must_be_positive(field: str):
    kwargs = {
        'container': 'raw',
        'account_name': 'acct',
        'credential': 'token',
        field: 0,
    }
    with pytest.raises(ValueError):
        get_storage('azure', **kwargs)


def test_azure_missing_config_raises_helpfully(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    monkeypatch.chdir(tmp_path)  # hermetic: a developer .env must not leak in
    for var in (
        'STORIX_AZURE_CONTAINER',
        'STORIX_AZURE_ACCOUNT_NAME',
        'STORIX_AZURE_CREDENTIAL',
    ):
        monkeypatch.delenv(var, raising=False)
    with pytest.raises(ConfigurationError) as excinfo:
        get_storage('azure')
    message = str(excinfo.value)
    assert 'container' in message
    assert 'STORIX_AZURE_' in message


def test_s3_from_kwargs_builds_without_network():
    fs = get_storage('s3', bucket='raw', region='us-east-1', access_key_id='k')
    backend = fs.backend
    assert type(backend).__name__ == 'S3Backend'
    assert backend.locate(PurePosixPath('/x.txt')) == 's3://raw/x.txt'


def test_s3_root_prefix_shows_in_locate():
    fs = get_storage('s3', bucket='raw', region='r', root='/tenants/a')
    assert fs.backend.locate(PurePosixPath('/x')) == 's3://raw/tenants/a/x'


def test_s3_missing_config_raises_helpfully(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    monkeypatch.chdir(tmp_path)  # hermetic: a developer .env must not leak in
    monkeypatch.delenv('STORIX_S3_BUCKET', raising=False)
    with pytest.raises(ConfigurationError) as excinfo:
        get_storage('s3')
    message = str(excinfo.value)
    assert 'bucket' in message
    assert 'STORIX_S3_' in message


def test_gcs_from_kwargs_builds_without_network():
    fs = get_storage('gcs', bucket='raw')
    backend = fs.backend
    assert type(backend).__name__ == 'GcsBackend'
    assert backend.locate(PurePosixPath('/x.txt')) == 'gs://raw/x.txt'


def test_gcs_missing_config_raises_helpfully(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    monkeypatch.chdir(tmp_path)  # hermetic: a developer .env must not leak in
    monkeypatch.delenv('STORIX_GCS_BUCKET', raising=False)
    with pytest.raises(ConfigurationError) as excinfo:
        get_storage('gcs')
    message = str(excinfo.value)
    assert 'bucket' in message
    assert 'STORIX_GCS_' in message


def test_unknown_provider_raises():
    with pytest.raises(ConfigurationError):
        get_storage('carrier-pigeon')


def test_keyword_provider_is_rejected_not_swallowed():
    """provider= must never silently become a config override."""
    with pytest.raises(ConfigurationError, match='positionally'):
        get_storage(provider='azure')  # type: ignore[call-overload]


def test_available_providers_lists_builtins_and_plugins():
    from storix._sync.factory import available_providers, register_backend

    assert set(available_providers()) >= {'local', 'memory', 'azure'}

    register_backend('unit-avail', lambda **_: MemoryBackend())
    try:
        assert 'unit-avail' in available_providers()
    finally:
        from storix._sync.factory import _BUILDERS

        _BUILDERS.pop('unit-avail')


def test_configuration_error_is_a_storage_error():
    assert issubclass(ConfigurationError, StorageError)


def test_register_backend_extends_the_factory():
    from storix._sync.backends.memory import MemoryBackend
    from storix._sync.factory import _BUILDERS, register_backend

    received: dict[str, str] = {}

    def build(**overrides: str) -> MemoryBackend:
        received.update(overrides)
        return MemoryBackend()

    register_backend('unit-test', build)
    try:
        fs = get_storage('unit-test', flavor='x')
        assert isinstance(fs.backend, MemoryBackend)
        assert received == {'flavor': 'x'}
    finally:
        _BUILDERS.pop('unit-test')
