# DO NOT EDIT - GENERATED by scripts/unasync.py
# source of truth: tests/_async/test_factory.py
from pathlib import Path

import pytest

from storix._sync import Storix, get_storage
from storix._sync.backends.local import LocalBackend
from storix.errors import ConfigurationError, StorageError


def test_default_is_local(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    monkeypatch.setenv('STORIX_LOCAL_BASE', str(tmp_path))
    fs = get_storage()
    assert isinstance(fs, Storix)
    assert isinstance(fs.backend, LocalBackend)
    assert fs.backend._base == tmp_path


def test_provider_argument_overrides_env(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    monkeypatch.setenv('STORIX_PROVIDER', 'azure')
    fs = get_storage('local', base=str(tmp_path))
    assert isinstance(fs.backend, LocalBackend)


def test_kwargs_override_env(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    monkeypatch.setenv('STORIX_LOCAL_BASE', '/definitely/not/this')
    fs = get_storage('local', base=str(tmp_path))
    assert fs.backend._base == tmp_path


def test_env_selects_provider(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    monkeypatch.setenv('STORIX_PROVIDER', 'local')
    monkeypatch.setenv('STORIX_LOCAL_BASE', str(tmp_path))
    assert isinstance(get_storage().backend, LocalBackend)


def test_azure_from_kwargs_builds_without_network():
    fs = get_storage('azure', container='raw', account_name='acct', credential='token')
    assert fs.backend.container == 'raw'


def test_azure_missing_config_raises_helpfully(monkeypatch: pytest.MonkeyPatch):
    for var in (
        'STORIX_AZURE_CONTAINER',
        'STORIX_AZURE_ACCOUNT_NAME',
        'STORIX_AZURE_CREDENTIAL',
    ):
        monkeypatch.delenv(var, raising=False)
    with pytest.raises(ConfigurationError) as excinfo:
        get_storage('azure')
    message = str(excinfo.value)
    assert 'container' in message
    assert 'STORIX_AZURE_' in message


def test_unknown_provider_raises():
    with pytest.raises(ConfigurationError):
        get_storage('carrier-pigeon')  # type: ignore[arg-type]


def test_configuration_error_is_a_storage_error():
    assert issubclass(ConfigurationError, StorageError)
