# DO NOT EDIT - GENERATED by scripts/unasync.py
# source of truth: tests/_async/test_temporary.py
from pathlib import Path

from storix._sync import temporary


def test_temporary_round_trip_and_cleanup():
    with temporary() as fs:
        base = Path(fs.backend._base)
        assert base.exists()
        fs.echo(b'scratch', '/a.txt')
        assert fs.cat('/a.txt') == b'scratch'
    assert not base.exists()


def test_temporary_sessions_are_isolated():
    with temporary() as one, temporary() as two:
        one.touch('/only-in-one')
        assert not two.exists('/only-in-one')
