# DO NOT EDIT - GENERATED by scripts/unasync.py
# source of truth: tests/_async/test_stream.py
import io

from collections.abc import Iterator

import pytest

from storix._sync._stream import chunked, collect, ensure_chunks, iter_chunks


def _astream(*chunks: bytes) -> Iterator[bytes]:
    yield from chunks


def test_collect_joins_chunks():
    assert collect(_astream(b'hello ', b'world')) == b'hello world'


def test_collect_empty_stream():
    assert collect(_astream()) == b''


def test_chunked_exact_division():
    assert list(chunked(b'abcdef', size=2)) == [b'ab', b'cd', b'ef']


def test_chunked_remainder():
    assert list(chunked(b'abcde', size=2)) == [b'ab', b'cd', b'e']


def test_chunked_empty():
    assert list(chunked(b'', size=2)) == []


def test_chunked_accepts_bytearray_and_yields_bytes():
    chunks = list(chunked(bytearray(b'abcd'), size=3))
    assert chunks == [b'abc', b'd']
    assert all(type(c) is bytes for c in chunks)


def test_chunked_accepts_memoryview():
    assert list(chunked(memoryview(b'abcd'), size=2)) == [b'ab', b'cd']


def _drain(data) -> bytes:
    return b''.join(list(ensure_chunks(data)))


def test_ensure_chunks_scalars():
    assert _drain(b'raw bytes') == b'raw bytes'
    assert _drain('text encodes') == b'text encodes'
    assert _drain(bytearray(b'buffer')) == b'buffer'


def test_ensure_chunks_iterable_of_mixed_chunks():
    assert _drain([b'a', 'b', b'c']) == b'abc'


def test_ensure_chunks_file_like():
    assert _drain(io.BytesIO(b'from a file')) == b'from a file'


def test_ensure_chunks_async_iterable():
    def agen() -> Iterator[bytes]:
        yield b'async '
        yield b'chunks'

    assert _drain(agen()) == b'async chunks'


def test_ensure_chunks_rejects_unsupported_items():
    with pytest.raises(TypeError):
        _drain([1, 2, 3])


def test_iter_chunks_reads_file_like_in_chunks():
    assert b''.join(iter_chunks(io.BytesIO(b'x' * 10))) == b'x' * 10
