# DO NOT EDIT - GENERATED by scripts/unasync.py
# source of truth: tests/_async/test_core.py
# ruff: noqa: A004
from pathlib import Path, PurePosixPath as P

import pytest

from storix._sync import Storix
from storix._sync.backends.local import LocalBackend
from storix._sync.backends.memory import MemoryBackend
from storix.errors import (
    AlreadyExistsError,
    DirectoryNotEmptyError,
    IsADirectoryError,
    NotADirectoryError,
    PathNotFoundError,
    UnsupportedOperationError,
)
from storix.models import FileProperties


@pytest.fixture(params=['memory', 'local'])
def fs(request: pytest.FixtureRequest, tmp_path: Path) -> Storix:
    """The whole core suite runs against every backend."""
    if request.param == 'memory':
        return Storix(MemoryBackend())
    return Storix(LocalBackend(tmp_path))


# --- construction ---


def test_layers_kwarg_wraps_the_backend():
    from functools import partial

    from storix._sync import SandboxLayer

    inner = MemoryBackend()
    inner.make_dir(P('/jail'), parents=False)
    fs = Storix(inner, layers=[partial(SandboxLayer, root='/jail')])

    fs.touch('/a.txt')
    assert inner.exists(P('/jail/a.txt'))


def test_with_layer_returns_a_new_wrapped_session():
    from functools import partial

    from storix._sync import SandboxLayer

    inner = MemoryBackend()
    inner.make_dir(P('/jail'), parents=False)

    fs = Storix(inner)
    jailed = fs.with_layer(partial(SandboxLayer, root='/jail'))

    jailed.touch('/a.txt')
    assert inner.exists(P('/jail/a.txt'))
    assert fs.exists('/jail/a.txt')  # original session untouched


def test_resolve_returns_session_absolute_path(fs: Storix):
    fs.mkdir('/docs')
    fs.cd('/docs')
    assert str(fs.resolve('a.txt')) == '/docs/a.txt'
    assert str(fs.resolve('~/b.txt')) == '/b.txt'
    assert str(fs.resolve()) == '/docs'


# --- identity & navigation ---


def test_defaults(fs: Storix):
    assert str(fs.root) == '/'
    assert str(fs.home) == '/'
    assert str(fs.pwd()) == '/'


def test_cd_into_directory(fs: Storix):
    fs.mkdir('/docs')
    fs.cd('/docs')
    assert str(fs.pwd()) == '/docs'


def test_cd_none_returns_home(fs: Storix):
    fs.mkdir('/docs')
    fs.cd('/docs')
    fs.cd()
    assert fs.pwd() == fs.home


def test_cd_into_file_raises(fs: Storix):
    fs.touch('/a.txt')
    with pytest.raises(NotADirectoryError):
        fs.cd('/a.txt')


def test_cd_missing_raises(fs: Storix):
    with pytest.raises(PathNotFoundError):
        fs.cd('/nope')


def test_relative_paths_resolve_against_cwd(fs: Storix):
    fs.mkdir('/docs')
    fs.cd('/docs')
    fs.touch('a.txt')
    assert fs.exists('/docs/a.txt')
    assert fs.exists('../docs/a.txt')


def test_tilde_resolves_against_home(fs: Storix):
    backend = MemoryBackend()
    scoped = Storix(backend, home='/h')
    Storix(backend).mkdir('/h')
    scoped.touch('~/a.txt')
    assert scoped.exists('/h/a.txt')


# --- ls ---


def test_ls_hides_dotfiles_by_default(fs: Storix):
    fs.touch('/a.txt', '/.env')
    names = {str(p) for p in fs.ls('/')}
    assert names == {'a.txt'}


def test_ls_all_shows_hidden(fs: Storix):
    fs.touch('/a.txt', '/.env')
    names = {str(p) for p in fs.ls('/', all=True)}
    assert names == {'a.txt', '.env'}


def test_ls_abs_returns_full_paths(fs: Storix):
    fs.mkdir('/docs')
    fs.touch('/docs/a.txt')
    assert fs.ls('/docs', abs=True) == [P('/docs/a.txt')]


def test_ls_on_file_returns_the_file(fs: Storix):
    fs.touch('/a.txt')
    assert fs.ls('/a.txt') == [P('a.txt')]
    assert fs.ls('/a.txt', abs=True) == [P('/a.txt')]


def test_ls_missing_raises(fs: Storix):
    with pytest.raises(PathNotFoundError):
        fs.ls('/nope')


# --- cat ---


def test_cat_single(fs: Storix):
    fs.echo(b'hello', '/a.txt')
    assert fs.cat('/a.txt') == b'hello'


def test_cat_concatenates_in_order(fs: Storix):
    fs.echo(b'one', '/a.txt')
    fs.echo(b'two', '/b.txt')
    assert fs.cat('/a.txt', '/b.txt') == b'onetwo'


# --- touch ---


def test_touch_creates_empty_files_variadic(fs: Storix):
    fs.touch('/a.txt', '/b.txt')
    assert fs.cat('/a.txt') == b''
    assert fs.cat('/b.txt') == b''


def test_touch_preserves_content_and_refreshes_mtime(fs: Storix):
    fs.echo(b'content', '/a.txt')
    before = fs.stat('/a.txt')
    fs.touch('/a.txt')
    after = fs.stat('/a.txt')
    assert fs.cat('/a.txt') == b'content'
    assert after.modified >= before.modified


def test_touch_missing_parent_raises(fs: Storix):
    with pytest.raises(PathNotFoundError) as excinfo:
        fs.touch('/missing/a.txt')
    assert str(excinfo.value.path) == '/missing'


# --- echo ---


def test_echo_overwrites(fs: Storix):
    fs.echo(b'old', '/a.txt')
    fs.echo(b'new', '/a.txt')
    assert fs.cat('/a.txt') == b'new'


def test_echo_appends(fs: Storix):
    fs.echo(b'hello ', '/a.txt')
    fs.echo(b'world', '/a.txt', mode='a')
    assert fs.cat('/a.txt') == b'hello world'


def test_echo_encodes_str(fs: Storix):
    fs.echo('text data', '/a.txt')
    assert fs.cat('/a.txt') == b'text data'


def test_echo_accepts_iterable_of_chunks(fs: Storix):
    fs.echo([b'a', b'b', b'c'], '/a.txt')
    assert fs.cat('/a.txt') == b'abc'


def test_echo_content_type_requires_capability(fs: Storix):
    with pytest.raises(UnsupportedOperationError) as excinfo:
        fs.echo(b'x', '/a.txt', content_type='text/plain')
    assert excinfo.value.operation == 'content_type'


def test_echo_metadata_follows_capability(fs: Storix):
    if fs.backend.capabilities.custom_metadata:
        fs.echo(b'x', '/m.txt', metadata={'owner': 'tests'})
        assert (fs.stat('/m.txt')).metadata == {'owner': 'tests'}
    else:
        with pytest.raises(UnsupportedOperationError) as excinfo:
            fs.echo(b'x', '/m.txt', metadata={'owner': 'tests'})
        assert excinfo.value.operation == 'custom_metadata'


def test_set_metadata_merge(fs: Storix):
    if not fs.backend.capabilities.custom_metadata:
        with pytest.raises(UnsupportedOperationError):
            fs.set_metadata('/m.txt', {'a': '1'})
        return

    fs.echo(b'x', '/m.txt', metadata={'a': '1', 'b': '2'})
    fs.set_metadata('/m.txt', {'b': '9', 'c': '3'}, merge=True)
    assert (fs.stat('/m.txt')).metadata == {'a': '1', 'b': '9', 'c': '3'}

    fs.set_metadata('/m.txt', {'only': 'this'})  # replace, not merge
    assert (fs.stat('/m.txt')).metadata == {'only': 'this'}


def test_url_requires_capability(fs: Storix):
    fs.touch('/a.txt')
    with pytest.raises(UnsupportedOperationError) as excinfo:
        fs.url('/a.txt')
    assert excinfo.value.operation == 'presigned_urls'


def test_data_url_works_on_any_backend(fs: Storix):
    fs.echo(b'hello', '/a.txt')
    url = fs.data_url('/a.txt')
    assert url.startswith('data:')
    assert url.endswith('aGVsbG8=')  # base64('hello')


def test_echo_missing_parent_raises(fs: Storix):
    with pytest.raises(PathNotFoundError):
        fs.echo(b'x', '/missing/a.txt')


# --- mkdir ---


def test_mkdir_variadic(fs: Storix):
    fs.mkdir('/a', '/b')
    assert fs.isdir('/a')
    assert fs.isdir('/b')


def test_mkdir_parents(fs: Storix):
    fs.mkdir('/a/b/c', parents=True)
    assert fs.isdir('/a/b/c')


def test_mkdir_existing_raises(fs: Storix):
    fs.mkdir('/a')
    with pytest.raises(AlreadyExistsError):
        fs.mkdir('/a')


# --- rm / rmdir ---


def test_rm_files_variadic(fs: Storix):
    fs.touch('/a.txt', '/b.txt')
    fs.rm('/a.txt', '/b.txt')
    assert not fs.exists('/a.txt')
    assert not fs.exists('/b.txt')


def test_rm_directory_without_recursive_raises(fs: Storix):
    fs.mkdir('/d')
    with pytest.raises(IsADirectoryError):
        fs.rm('/d')


def test_rm_recursive_removes_tree(fs: Storix):
    fs.mkdir('/d/sub', parents=True)
    fs.touch('/d/a.txt', '/d/sub/b.txt')
    fs.rm('/d', recursive=True)
    assert not fs.exists('/d')


def test_rm_validates_all_before_deleting(fs: Storix):
    """One bad target means nothing gets deleted."""
    fs.touch('/a.txt')
    fs.mkdir('/d')
    with pytest.raises(IsADirectoryError):
        fs.rm('/a.txt', '/d')
    assert fs.exists('/a.txt')


def test_rm_missing_raises(fs: Storix):
    with pytest.raises(PathNotFoundError):
        fs.rm('/nope')


def test_rmdir_removes_empty_directories(fs: Storix):
    fs.mkdir('/a', '/b')
    fs.rmdir('/a', '/b')
    assert not fs.exists('/a')


def test_rmdir_non_empty_raises(fs: Storix):
    fs.mkdir('/d')
    fs.touch('/d/a.txt')
    with pytest.raises(DirectoryNotEmptyError):
        fs.rmdir('/d')


def test_rmdir_on_file_raises(fs: Storix):
    fs.touch('/a.txt')
    with pytest.raises(NotADirectoryError):
        fs.rmdir('/a.txt')


# --- mv ---


def test_mv_renames_file(fs: Storix):
    fs.echo(b'payload', '/old.txt')
    fs.mv('/old.txt', '/new.txt')
    assert fs.cat('/new.txt') == b'payload'
    assert not fs.exists('/old.txt')


def test_mv_into_existing_directory(fs: Storix):
    fs.echo(b'x', '/a.txt')
    fs.mkdir('/archive')
    fs.mv('/a.txt', '/archive')
    assert fs.exists('/archive/a.txt')


def test_mv_multiple_sources_into_directory(fs: Storix):
    fs.touch('/a.txt', '/b.txt')
    fs.mkdir('/archive')
    fs.mv('/a.txt', '/b.txt', '/archive')
    assert fs.exists('/archive/a.txt')
    assert fs.exists('/archive/b.txt')


def test_mv_multiple_sources_require_directory_destination(fs: Storix):
    fs.touch('/a.txt', '/b.txt', '/target.txt')
    with pytest.raises(NotADirectoryError):
        fs.mv('/a.txt', '/b.txt', '/target.txt')


def test_mv_moves_directory_tree(fs: Storix):
    fs.mkdir('/d/sub', parents=True)
    fs.echo(b'x', '/d/sub/a.txt')
    fs.mv('/d', '/renamed')
    assert fs.cat('/renamed/sub/a.txt') == b'x'
    assert not fs.exists('/d')


def test_mv_requires_destination(fs: Storix):
    with pytest.raises(TypeError):
        fs.mv('/only-one')


def test_mv_missing_source_raises(fs: Storix):
    with pytest.raises(PathNotFoundError):
        fs.mv('/nope', '/dst')


# --- cp ---


def test_cp_file(fs: Storix):
    fs.echo(b'payload', '/a.txt')
    fs.cp('/a.txt', '/b.txt')
    assert fs.cat('/b.txt') == b'payload'
    assert fs.cat('/a.txt') == b'payload'


def test_cp_into_existing_directory(fs: Storix):
    fs.echo(b'x', '/a.txt')
    fs.mkdir('/backup')
    fs.cp('/a.txt', '/backup')
    assert fs.exists('/backup/a.txt')


def test_cp_directory_without_recursive_raises(fs: Storix):
    fs.mkdir('/d')
    with pytest.raises(IsADirectoryError):
        fs.cp('/d', '/copy')


def test_cp_recursive_copies_tree(fs: Storix):
    fs.mkdir('/d/sub', parents=True)
    fs.echo(b'x', '/d/sub/a.txt')
    fs.cp('/d', '/copy', recursive=True)
    assert fs.cat('/copy/sub/a.txt') == b'x'
    assert fs.cat('/d/sub/a.txt') == b'x'


def test_cp_requires_destination(fs: Storix):
    with pytest.raises(TypeError):
        fs.cp('/only-one')


# --- stat / du / predicates ---


def test_stat_shapes_file_properties(fs: Storix):
    fs.echo(b'12345', '/a.txt')
    props = fs.stat('/a.txt')
    assert isinstance(props, FileProperties)
    assert props.name == 'a.txt'
    assert props.size == 5
    assert props.kind == 'file'


def test_stat_root_has_a_name(fs: Storix):
    props = fs.stat('/')
    assert props.name == '/'
    assert props.kind == 'directory'


def test_du_sums_tree(fs: Storix):
    fs.mkdir('/d')
    fs.echo(b'123', '/d/a.txt')
    fs.echo(b'45', '/d/b.txt')
    assert fs.du('/d') == 5


def test_context_manager_closes_backend():
    class _ClosingBackend(MemoryBackend):
        closed = False

        def close(self) -> None:
            self.closed = True

    backend = _ClosingBackend()
    with Storix(backend) as fs:
        fs.touch('/a.txt')
    assert backend.closed


def test_predicates(fs: Storix):
    fs.touch('/a.txt')
    fs.mkdir('/d')
    assert fs.isfile('/a.txt')
    assert not fs.isfile('/d')
    assert not fs.isfile('/nope')
    assert fs.isdir('/d')
    assert not fs.isdir('/a.txt')
    assert not fs.isdir('/nope')
