# DO NOT EDIT - GENERATED by scripts/unasync.py
# source of truth: tests/_async/test_layers.py
from collections.abc import Iterator
from pathlib import PurePosixPath as P

import pytest

from storix._sync.backends import StorageBackend
from storix._sync.backends.memory import MemoryBackend
from storix._sync.layers import LayerBase, SandboxLayer
from storix.errors import PathNotFoundError
from storix.types import EchoMode


def _astream(*chunks: bytes) -> Iterator[bytes]:
    yield from chunks


def put(
    backend: StorageBackend, path: str, data: bytes = b'', mode: EchoMode = 'w'
) -> None:
    backend.write(P(path), _astream(data), mode=mode, content_type=None)


@pytest.fixture
def jailed() -> tuple[MemoryBackend, SandboxLayer]:
    inner = MemoryBackend()
    inner.make_dir(P('/jail'), parents=False)
    return inner, SandboxLayer(inner, root='/jail')


def test_satisfies_protocol():
    # the annotation is the test: type checkers verify structural conformance
    layer: StorageBackend = SandboxLayer(MemoryBackend(), root='/')
    assert layer.capabilities.content_type is False


def test_passthrough_layer_satisfies_protocol_and_delegates():
    base: StorageBackend = LayerBase(MemoryBackend())  # static conformance
    put(base, '/a.txt', b'through')
    assert base.read(P('/a.txt')) == b'through'
    assert base.capabilities.custom_metadata is True  # inherited from memory


def test_paths_are_anchored_under_root(
    jailed: tuple[MemoryBackend, SandboxLayer],
):
    inner, layer = jailed
    put(layer, '/a.txt', b'scoped')
    assert inner.read(P('/jail/a.txt')) == b'scoped'
    assert layer.read(P('/a.txt')) == b'scoped'


def test_traversal_cannot_escape(jailed: tuple[MemoryBackend, SandboxLayer]):
    inner, layer = jailed
    inner.make_dir(P('/secret'), parents=False)
    put(inner, '/secret/key.txt', b'nope')

    # '..' bypassing the core clamps at the virtual root, not the real one
    with pytest.raises(PathNotFoundError):
        layer.read(P('/../secret/key.txt'))


def test_errors_are_rescoped_to_virtual_paths(
    jailed: tuple[MemoryBackend, SandboxLayer],
):
    _, layer = jailed
    with pytest.raises(PathNotFoundError) as excinfo:
        layer.stat(P('/nope'))
    assert str(excinfo.value.path) == '/nope'
    assert 'jail' not in str(excinfo.value)


def test_rescopes_parent_paths_from_inner_errors(
    jailed: tuple[MemoryBackend, SandboxLayer],
):
    _, layer = jailed
    with pytest.raises(PathNotFoundError) as excinfo:
        layer.make_dir(P('/missing/child'), parents=False)
    assert str(excinfo.value.path) == '/missing'


def test_translation_is_public_for_audit(
    jailed: tuple[MemoryBackend, SandboxLayer],
):
    """The audit pattern: the layer owner records real paths; the
    sandboxed session only ever sees virtual ones.
    """
    from storix._sync import Storix

    inner, layer = jailed
    fs = Storix(layer)
    fs.mkdir('/videos')
    fs.cd('/videos')
    fs.echo(b'...', 'abc123.mp4')

    audit_path = layer.to_real(fs.resolve('abc123.mp4'))
    assert str(audit_path) == '/jail/videos/abc123.mp4'
    assert inner.exists(audit_path)

    # and back: reconstruct the virtual name from the audited real path
    assert str(layer.to_virtual(audit_path)) == '/videos/abc123.mp4'


def test_layers_compose(jailed: tuple[MemoryBackend, SandboxLayer]):
    inner, layer = jailed
    layer.make_dir(P('/deeper'), parents=False)
    nested = SandboxLayer(layer, root='/deeper')
    put(nested, '/a.txt', b'twice jailed')
    assert inner.read(P('/jail/deeper/a.txt')) == b'twice jailed'


# --- native-preference combinator ---


def test_when_missing_wraps_only_capability_poor_backends():
    from storix._sync.layers import DataUrlLayer, when_missing
    from storix.enums import Capability

    build = when_missing(Capability.PRESIGNED_URLS, DataUrlLayer)

    # memory lacks presigned_urls -> wrapped and upgraded
    wrapped = build(MemoryBackend())
    assert isinstance(wrapped, DataUrlLayer)
    assert wrapped.capabilities.presigned_urls is True

    # a backend that already has it -> returned untouched (zero overhead)
    native = DataUrlLayer(MemoryBackend())  # now advertises presigned_urls
    assert build(native) is native


def test_with_layer_unless_prefers_native():
    from storix._sync import Storix
    from storix._sync.layers import DataUrlLayer
    from storix.enums import Capability

    inner = MemoryBackend()  # no presigned_urls
    fs = Storix(inner).with_layer(DataUrlLayer, unless=Capability.PRESIGNED_URLS)
    fs.echo(b'x', '/a.txt')
    assert (fs.url('/a.txt')).startswith('data:')

    # if the backend already had the capability, the layer is skipped:
    native = DataUrlLayer(MemoryBackend())
    fs2 = Storix(native).with_layer(DataUrlLayer, unless=Capability.PRESIGNED_URLS)
    assert isinstance(fs2.backend, DataUrlLayer)  # only one layer, not two


# --- DataUrlLayer ---


def test_dataurl_layer_makes_urls_on_any_backend():
    from storix._sync import Storix
    from storix._sync.layers import DataUrlLayer

    fs = Storix(DataUrlLayer(MemoryBackend()))
    fs.echo(b'hello', '/a.txt')
    url = fs.url('/a.txt')
    assert url.startswith('data:')
    assert url.endswith('aGVsbG8=')  # base64('hello')


# --- MetadataLayer sidecar ---


def test_metadata_layer_sidecar_is_invisible():
    from storix._sync import Storix
    from storix._sync.layers import MetadataLayer

    fs = Storix(MetadataLayer(MemoryBackend()))
    fs.echo(b'x', '/a.txt', metadata={'owner': 'me'})

    # metadata round-trips, but the sidecar never surfaces
    assert (fs.stat('/a.txt')).metadata == {'owner': 'me'}
    assert fs.ls('/', all=True) == [P('a.txt')]
    assert not fs.exists('/.storix-meta.json')
    assert fs.du('/') == 1  # sidecar bytes excluded


def test_metadata_layer_move_rekeys_sidecar():
    from storix._sync import Storix
    from storix._sync.layers import MetadataLayer

    fs = Storix(MetadataLayer(MemoryBackend()))
    fs.echo(b'x', '/a.txt', metadata={'k': 'v'})
    fs.mv('/a.txt', '/b.txt')

    assert (fs.stat('/b.txt')).metadata == {'k': 'v'}
    assert not fs.exists('/a.txt')


def test_metadata_layer_accepts_custom_serializer():
    from storix._sync import Storix
    from storix._sync.layers import MetadataLayer

    calls: list[str] = []

    class RecordingSerializer:
        def dumps(self, obj: object) -> bytes:
            calls.append('dumps')
            import json

            return json.dumps(obj).encode()

        def loads(self, data: bytes) -> object:
            calls.append('loads')
            import json

            return json.loads(data)

    fs = Storix(MetadataLayer(MemoryBackend(), serializer=RecordingSerializer()))
    fs.echo(b'x', '/a.txt', metadata={'k': 'v'})
    assert (fs.stat('/a.txt')).metadata == {'k': 'v'}
    assert 'dumps' in calls and 'loads' in calls  # the custom codec ran


def test_metadata_layer_delete_drops_sidecar_entry():
    from storix._sync import Storix
    from storix._sync.layers import MetadataLayer

    inner = MemoryBackend()
    fs = Storix(MetadataLayer(inner))
    fs.echo(b'x', '/a.txt', metadata={'k': 'v'})
    fs.rm('/a.txt')

    # recreating without metadata must not resurrect the old entry
    fs.echo(b'y', '/a.txt')
    assert (fs.stat('/a.txt')).metadata is None
