# DO NOT EDIT - GENERATED by scripts/unasync.py
# source of truth: tests/_async/test_layers.py
from collections.abc import Iterator
from pathlib import PurePosixPath as P

import pytest

from storix._sync.backends import StorageBackend
from storix._sync.backends.memory import MemoryBackend
from storix._sync.layers import LayerBase, SandboxLayer
from storix.errors import PathNotFoundError
from storix.types import EchoMode


def _astream(*chunks: bytes) -> Iterator[bytes]:
    yield from chunks


def put(
    backend: StorageBackend, path: str, data: bytes = b'', mode: EchoMode = 'w'
) -> None:
    backend.write(P(path), _astream(data), mode=mode, content_type=None)


@pytest.fixture
def jailed() -> tuple[MemoryBackend, SandboxLayer]:
    inner = MemoryBackend()
    inner.make_dir(P('/jail'), parents=False)
    return inner, SandboxLayer(inner, root='/jail')


def test_satisfies_protocol():
    # the annotation is the test: type checkers verify structural conformance
    layer: StorageBackend = SandboxLayer(MemoryBackend(), root='/')
    assert layer.capabilities.content_type is False


def test_passthrough_layer_satisfies_protocol_and_delegates():
    base: StorageBackend = LayerBase(MemoryBackend())  # static conformance
    put(base, '/a.txt', b'through')
    assert base.read(P('/a.txt')) == b'through'
    assert base.capabilities.custom_metadata is True  # inherited from memory


def test_paths_are_anchored_under_root(
    jailed: tuple[MemoryBackend, SandboxLayer],
):
    inner, layer = jailed
    put(layer, '/a.txt', b'scoped')
    assert inner.read(P('/jail/a.txt')) == b'scoped'
    assert layer.read(P('/a.txt')) == b'scoped'


def test_traversal_cannot_escape(jailed: tuple[MemoryBackend, SandboxLayer]):
    inner, layer = jailed
    inner.make_dir(P('/secret'), parents=False)
    put(inner, '/secret/key.txt', b'nope')

    # '..' bypassing the core clamps at the virtual root, not the real one
    with pytest.raises(PathNotFoundError):
        layer.read(P('/../secret/key.txt'))


def test_errors_are_rescoped_to_virtual_paths(
    jailed: tuple[MemoryBackend, SandboxLayer],
):
    _, layer = jailed
    with pytest.raises(PathNotFoundError) as excinfo:
        layer.stat(P('/nope'))
    assert str(excinfo.value.path) == '/nope'
    assert 'jail' not in str(excinfo.value)


def test_rescopes_parent_paths_from_inner_errors(
    jailed: tuple[MemoryBackend, SandboxLayer],
):
    _, layer = jailed
    with pytest.raises(PathNotFoundError) as excinfo:
        layer.make_dir(P('/missing/child'), parents=False)
    assert str(excinfo.value.path) == '/missing'


def test_translation_is_public_for_audit(
    jailed: tuple[MemoryBackend, SandboxLayer],
):
    """The audit pattern: the layer owner records real paths; the
    sandboxed session only ever sees virtual ones.
    """
    from storix._sync import Storix

    inner, layer = jailed
    fs = Storix(layer)
    fs.mkdir('/videos')
    fs.cd('/videos')
    fs.echo(b'...', 'abc123.mp4')

    audit_path = layer.to_real(fs.resolve('abc123.mp4'))
    assert str(audit_path) == '/jail/videos/abc123.mp4'
    assert inner.exists(audit_path)

    # and back: reconstruct the virtual name from the audited real path
    assert str(layer.to_virtual(audit_path)) == '/videos/abc123.mp4'


def test_layers_compose(jailed: tuple[MemoryBackend, SandboxLayer]):
    inner, layer = jailed
    layer.make_dir(P('/deeper'), parents=False)
    nested = SandboxLayer(layer, root='/deeper')
    put(nested, '/a.txt', b'twice jailed')
    assert inner.read(P('/jail/deeper/a.txt')) == b'twice jailed'


# --- native-preference combinator ---


def test_when_missing_wraps_only_capability_poor_backends():
    from storix._sync.layers import DataUrlLayer, when_missing
    from storix.enums import Capability

    build = when_missing(Capability.PRESIGNED_URLS, DataUrlLayer)

    # memory lacks presigned_urls -> wrapped and upgraded
    wrapped = build(MemoryBackend())
    assert isinstance(wrapped, DataUrlLayer)
    assert wrapped.capabilities.presigned_urls is True

    # a backend that already has it -> returned untouched (zero overhead)
    native = DataUrlLayer(MemoryBackend())  # now advertises presigned_urls
    assert build(native) is native


def test_with_layer_missing_infers_capability_and_prefers_native():
    from storix._sync import Storix
    from storix._sync.layers import DataUrlLayer

    inner = MemoryBackend()  # no presigned_urls
    fs = Storix(inner).with_layer_missing(DataUrlLayer)  # capability inferred
    fs.echo(b'x', '/a.txt')
    assert (fs.url('/a.txt')).startswith('data:')

    # if the backend already had the capability, the layer is skipped:
    native = DataUrlLayer(MemoryBackend())
    fs2 = Storix(native).with_layer_missing(DataUrlLayer)
    assert isinstance(fs2.backend, DataUrlLayer)  # only one layer, not two


def test_with_layer_missing_rejects_layers_without_provides():
    from storix._sync import Storix
    from storix._sync.layers import LayerBase

    with pytest.raises(ValueError, match='provides'):
        Storix(MemoryBackend()).with_layer_missing(LayerBase)


# --- DataUrlLayer ---


def test_dataurl_layer_makes_urls_on_any_backend():
    from storix._sync import Storix
    from storix._sync.layers import DataUrlLayer

    fs = Storix(DataUrlLayer(MemoryBackend()))
    fs.echo(b'hello', '/a.txt')
    url = fs.url('/a.txt')
    assert url.startswith('data:')
    assert url.endswith('aGVsbG8=')  # base64('hello')


# --- MetadataLayer sidecar ---


def test_metadata_layer_sidecar_is_invisible():
    from storix._sync import Storix
    from storix._sync.layers import MetadataLayer

    fs = Storix(MetadataLayer(MemoryBackend()))
    fs.echo(b'x', '/a.txt', metadata={'owner': 'me'})

    # metadata round-trips, but the sidecar never surfaces
    assert (fs.stat('/a.txt')).metadata == {'owner': 'me'}
    assert fs.ls('/', all=True) == [P('a.txt')]
    assert not fs.exists('/.storix-meta.json')
    assert fs.du('/') == 1  # sidecar bytes excluded


def test_metadata_layer_move_rekeys_sidecar():
    from storix._sync import Storix
    from storix._sync.layers import MetadataLayer

    fs = Storix(MetadataLayer(MemoryBackend()))
    fs.echo(b'x', '/a.txt', metadata={'k': 'v'})
    fs.mv('/a.txt', '/b.txt')

    assert (fs.stat('/b.txt')).metadata == {'k': 'v'}
    assert not fs.exists('/a.txt')


class RecordingSerializer:
    def __init__(self) -> None:
        self.calls: list[str] = []

    def dumps(self, obj: object) -> bytes:
        import json

        self.calls.append('dumps')
        return json.dumps(obj).encode()

    def loads(self, data: bytes) -> object:
        import json

        self.calls.append('loads')
        return json.loads(data)


def test_metadata_layer_accepts_custom_codec():
    from storix._sync import Storix
    from storix._sync.layers import MetadataLayer

    rec = RecordingSerializer()
    fs = Storix(
        MetadataLayer(MemoryBackend(), serialize=rec.dumps, deserialize=rec.loads)
    )
    fs.echo(b'x', '/a.txt', metadata={'k': 'v'})
    assert (fs.stat('/a.txt')).metadata == {'k': 'v'}
    assert 'dumps' in rec.calls and 'loads' in rec.calls


def test_with_layer_forwards_typed_kwargs_to_the_layer():
    from storix._sync import Storix
    from storix._sync.layers import MetadataLayer

    rec = RecordingSerializer()
    # serialize=/deserialize= forward (and type-check) straight through with_layer
    fs = Storix(MemoryBackend()).with_layer(
        MetadataLayer, serialize=rec.dumps, deserialize=rec.loads
    )
    fs.echo(b'x', '/a.txt', metadata={'k': 'v'})
    assert (fs.stat('/a.txt')).metadata == {'k': 'v'}
    assert rec.calls  # the injected codec was used


def test_metadata_layer_delete_drops_sidecar_entry():
    from storix._sync import Storix
    from storix._sync.layers import MetadataLayer

    inner = MemoryBackend()
    fs = Storix(MetadataLayer(inner))
    fs.echo(b'x', '/a.txt', metadata={'k': 'v'})
    fs.rm('/a.txt')

    # recreating without metadata must not resurrect the old entry
    fs.echo(b'y', '/a.txt')
    assert (fs.stat('/a.txt')).metadata is None


# --- CacheLayer ---


class CountingBackend(MemoryBackend):
    """MemoryBackend that counts inner stat/list_dir calls, to prove hits."""

    def __init__(self) -> None:
        super().__init__()
        self.stat_calls = 0
        self.list_calls = 0

    def stat(self, path):
        self.stat_calls += 1
        return super().stat(path)

    def list_dir(self, path):
        self.list_calls += 1
        yield from super().list_dir(path)


def test_cache_layer_serves_repeat_reads_from_memory():
    from storix._sync import Storix
    from storix._sync.layers import CacheLayer

    inner = CountingBackend()
    fs = Storix(CacheLayer(inner))
    fs.mkdir('/d')
    fs.touch('/d/a.txt')

    inner.stat_calls = inner.list_calls = 0
    for _ in range(3):
        fs.stat('/d/a.txt')
        fs.ls('/d')
    # 3 iterations, but each distinct path hits the inner backend once:
    # /d/a.txt (fs.stat) and /d (ls's internal kind check) -> 2 stats, 1 list
    assert inner.stat_calls == 2
    assert inner.list_calls == 1


def test_cache_layer_evicts_on_write():
    from storix._sync import Storix
    from storix._sync.layers import CacheLayer

    fs = Storix(CacheLayer(MemoryBackend()))
    fs.echo(b'one', '/a.txt')
    assert (fs.stat('/a.txt')).size == 3  # warms the cache
    fs.echo(b'seventeen bytes!!', '/a.txt')  # mutation must evict
    assert (fs.stat('/a.txt')).size == 17  # not a stale 3


def test_cache_layer_evicts_listing_on_new_file():
    from storix._sync import Storix
    from storix._sync.layers import CacheLayer

    fs = Storix(CacheLayer(MemoryBackend()))
    fs.mkdir('/d')
    assert fs.ls('/d') == []  # warms empty listing
    fs.touch('/d/a.txt')  # must evict the parent listing
    assert [p.name for p in fs.ls('/d')] == ['a.txt']


def test_cache_layer_caches_negative_then_evicts_on_create():
    from storix._sync import Storix
    from storix._sync.layers import CacheLayer

    fs = Storix(CacheLayer(MemoryBackend()))
    assert not fs.exists('/a.txt')  # caches 'absent'
    fs.touch('/a.txt')  # evicts the negative
    assert fs.exists('/a.txt')


def test_cache_layer_ttl_expires(monkeypatch: pytest.MonkeyPatch):
    from storix._sync import Storix
    from storix._sync.layers import CacheLayer

    clock = {'t': 1000.0}
    monkeypatch.setattr('time.monotonic', lambda: clock['t'])

    inner = CountingBackend()
    fs = Storix(CacheLayer(inner, ttl=30))
    fs.touch('/a.txt')
    inner.stat_calls = 0
    fs.stat('/a.txt')  # miss -> 1
    fs.stat('/a.txt')  # hit -> still 1
    assert inner.stat_calls == 1

    clock['t'] += 31  # advance the clock past the ttl
    fs.stat('/a.txt')  # expired -> re-fetch
    assert inner.stat_calls == 2


def test_cache_layer_uses_a_custom_store():
    from storix._sync import Storix
    from storix._sync.layers import CacheLayer, CacheStore, InMemoryCacheStore

    class RecordingStore(InMemoryCacheStore):
        def __init__(self) -> None:
            super().__init__()
            self.ops: list[str] = []

        def get(self, key, default=None):
            self.ops.append(f'get {key}')
            return super().get(key, default)

        def set(self, key, value, *, expire=None):
            self.ops.append(f'set {key}')
            super().set(key, value, expire=expire)

        def delete(self, key):
            self.ops.append(f'del {key}')
            super().delete(key)

    store: CacheStore = RecordingStore()  # structural conformance
    fs = Storix(CacheLayer(MemoryBackend(), store=store))
    fs.mkdir('/d')
    fs.stat('/d')  # miss -> set, then a warm read
    fs.stat('/d')  # hit

    assert any(o.startswith('set stat:/d') for o in store.ops)  # wrote through
    assert sum(o == 'get stat:/d' for o in store.ops) == 2  # both reads hit store
    # the mkdir evicted the parent listing through the same store:
    assert any(o.startswith('del list:/') for o in store.ops)


def test_inmemory_store_satisfies_the_protocol():
    from storix._sync.layers import CacheStore, InMemoryCacheStore

    store: CacheStore = InMemoryCacheStore()  # the annotation is the test
    assert store is not None
