# DO NOT EDIT - GENERATED by scripts/unasync.py
# source of truth: tests/_async/test_temporary.py
from pathlib import Path, PurePosixPath as P

from storix._sync import scratch, temporary
from storix._sync.backends.memory import MemoryBackend


def test_temporary_round_trip_and_cleanup():
    with temporary() as fs:
        base = Path(fs.backend._base)
        assert base.exists()
        fs.echo(b'scratch', '/a.txt')
        assert fs.cat('/a.txt') == b'scratch'
    assert not base.exists()


def test_temporary_sessions_are_isolated():
    with temporary() as one, temporary() as two:
        one.touch('/only-in-one')
        assert not two.exists('/only-in-one')


def test_scratch_works_on_any_backend_and_cleans_up():
    backend = MemoryBackend()
    with scratch(backend) as fs:
        fs.mkdir('/work')
        fs.echo(b'ephemeral', '/work/a.txt')
        assert fs.cat('/work/a.txt') == b'ephemeral'
    # the scratch subtree is gone; the backend itself survives
    assert list(backend.list_dir(P('/'))) == []
    assert backend.exists(P('/'))


def test_scratch_pinned_root_persists_and_is_reused():
    backend = MemoryBackend()
    with scratch(backend, root='/pinned') as fs:
        fs.touch('/a.txt')
    assert backend.exists(P('/pinned/a.txt'))  # pinned => survives exit

    with scratch(backend, root='/pinned') as fs:
        assert fs.exists('/a.txt')  # same workspace, reattached


def test_scratch_sessions_are_isolated_on_one_backend():
    backend = MemoryBackend()
    with scratch(backend) as one, scratch(backend) as two:
        one.touch('/only-in-one')
        assert not two.exists('/only-in-one')
