# DO NOT EDIT - GENERATED by scripts/unasync.py
# source of truth: tests/_async/backends/test_memory.py
"""Memory-backend specifics; shared behavior lives in test_backends.py."""

from collections.abc import Iterator, Mapping
from pathlib import PurePosixPath as P

import pytest

from storix._sync.backends import BackendBase, StorageBackend
from storix._sync.backends.memory import MemoryBackend
from storix.types import EchoMode


def _astream(*chunks: bytes) -> Iterator[bytes]:
    yield from chunks


def put(
    backend: MemoryBackend, path: str, data: bytes = b'', mode: EchoMode = 'w'
) -> None:
    backend.write_stream(P(path), _astream(data), mode=mode, content_type=None)


class WholeMemoryBackend(MemoryBackend):
    """Memory store exposing only whole-object I/O to exercise fallbacks."""

    read_stream = BackendBase.read_stream
    write_stream = BackendBase.write_stream

    def __init__(self) -> None:
        super().__init__()
        self.full_writes: list[bytes] = []

    def read(self, path: P) -> bytes:
        return b''.join(list(MemoryBackend.read_stream(self, path)))

    def write(
        self,
        path: P,
        data: bytes,
        *,
        mode: EchoMode,
        content_type: str | None,
        metadata: Mapping[str, str] | None = None,
    ) -> None:
        self.full_writes.append(data)
        MemoryBackend.write_stream(
            self,
            path,
            _astream(data),
            mode=mode,
            content_type=content_type,
            metadata=metadata,
        )


class MissingIOBackend(MemoryBackend):
    """Concrete structural backend with neither member of either I/O pair."""

    read = BackendBase.read
    read_stream = BackendBase.read_stream
    write = BackendBase.write
    write_stream = BackendBase.write_stream


def test_backendbase_is_abstract():
    with pytest.raises(TypeError):
        BackendBase()  # type: ignore[abstract]


def test_memory_satisfies_protocol():
    # the annotation is the test: type checkers verify structural conformance
    backend: StorageBackend = MemoryBackend()
    assert backend.capabilities.content_type is False


def test_whole_object_backend_gets_bounded_read_stream_fallback():
    backend = WholeMemoryBackend()
    backend.write(P('/a.txt'), b'abcdef', mode='w', content_type=None)

    chunks = list(backend.read_stream(P('/a.txt'), chunk_size=2))

    assert chunks == [b'ab', b'cd', b'ef']


def test_whole_object_backend_gets_single_write_fallback():
    backend = WholeMemoryBackend()

    backend.write_stream(
        P('/a.txt'),
        _astream(b'a', b'b', b'c'),
        chunk_size=2,
        mode='w',
        content_type=None,
    )

    assert backend.full_writes == [b'abc']
    assert backend.read(P('/a.txt')) == b'abc'


def test_backend_without_either_read_form_fails_clearly():
    backend = MissingIOBackend()

    with pytest.raises(NotImplementedError, match=r'read\(\) or read_stream\(\)'):
        backend.read(P('/a.txt'))
    with pytest.raises(NotImplementedError, match=r'read\(\) or read_stream\(\)'):
        list(backend.read_stream(P('/a.txt')))


def test_backend_without_either_write_form_fails_clearly():
    backend = MissingIOBackend()

    with pytest.raises(NotImplementedError, match=r'write\(\) or write_stream\(\)'):
        backend.write(P('/a.txt'), b'x', mode='w', content_type=None)
    with pytest.raises(NotImplementedError, match=r'write\(\) or write_stream\(\)'):
        backend.write_stream(P('/a.txt'), _astream(b'x'), mode='w', content_type=None)


def test_append_updates_modified_preserves_created():
    """Memory-specific: POSIX ctime shifts on append, so only the memory
    backend can promise creation-time stability across appends.
    """
    backend = MemoryBackend()
    put(backend, '/a.txt', b'x')
    before = backend.stat(P('/a.txt'))
    put(backend, '/a.txt', b'y', mode='a')
    after = backend.stat(P('/a.txt'))
    assert after.created == before.created
    assert after.modified >= before.modified
