# DO NOT EDIT - GENERATED by scripts/unasync.py
# source of truth: tests/_async/backends/test_memory.py
# ruff: noqa: A004
from collections.abc import Iterator
from pathlib import PurePosixPath as P

import pytest

from storix._sync.backends import BackendBase, StorageBackend
from storix._sync.backends.memory import MemoryBackend
from storix.errors import (
    AlreadyExistsError,
    DirectoryNotEmptyError,
    IsADirectoryError,
    NotADirectoryError,
    PathNotFoundError,
)
from storix.types import EchoMode


@pytest.fixture
def backend() -> MemoryBackend:
    return MemoryBackend()


def _astream(*chunks: bytes) -> Iterator[bytes]:
    yield from chunks


def put(
    backend: MemoryBackend, path: str, data: bytes = b'', mode: EchoMode = 'w'
) -> None:
    backend.write(P(path), _astream(data), mode=mode, content_type=None)


# --- conformance ---


def test_backendbase_is_abstract():
    with pytest.raises(TypeError):
        BackendBase()  # type: ignore[abstract]


def test_memory_satisfies_protocol():
    # the annotation is the test: type checkers verify structural conformance
    backend: StorageBackend = MemoryBackend()
    assert backend.capabilities.content_type is False


def test_root_exists_initially(backend: MemoryBackend):
    assert backend.exists(P('/'))
    assert not backend.exists(P('/anything'))


# --- write / read ---


def test_write_creates_and_read_round_trips(backend: MemoryBackend):
    put(backend, '/a.txt', b'hello')
    assert backend.read(P('/a.txt')) == b'hello'


def test_write_truncates_existing(backend: MemoryBackend):
    put(backend, '/a.txt', b'old content')
    put(backend, '/a.txt', b'new')
    assert backend.read(P('/a.txt')) == b'new'


def test_append_extends(backend: MemoryBackend):
    put(backend, '/a.txt', b'hello ')
    put(backend, '/a.txt', b'world', mode='a')
    assert backend.read(P('/a.txt')) == b'hello world'


def test_append_creates_missing(backend: MemoryBackend):
    put(backend, '/a.txt', b'created', mode='a')
    assert backend.read(P('/a.txt')) == b'created'


@pytest.mark.parametrize('mode', ['w', 'a'])
def test_write_onto_directory_raises(backend: MemoryBackend, mode: EchoMode):
    backend.make_dir(P('/d'), parents=False)
    with pytest.raises(IsADirectoryError):
        put(backend, '/d', b'x', mode=mode)


def test_read_missing_raises(backend: MemoryBackend):
    with pytest.raises(PathNotFoundError):
        backend.read(P('/nope'))


def test_read_directory_raises(backend: MemoryBackend):
    backend.make_dir(P('/d'), parents=False)
    with pytest.raises(IsADirectoryError):
        backend.read(P('/d'))


def test_read_stream_yields_content(backend: MemoryBackend):
    put(backend, '/a.txt', b'streamed')
    chunks = list(backend.read_stream(P('/a.txt')))
    assert b''.join(chunks) == b'streamed'


# --- list_dir ---


def test_list_dir_entries(backend: MemoryBackend):
    backend.make_dir(P('/d'), parents=False)
    backend.make_dir(P('/d/sub'), parents=False)
    put(backend, '/d/a.txt', b'12345')

    entries = {(e.name, e.is_dir, e.size) for e in backend.list_dir(P('/d'))}
    assert entries == {('sub', True, 0), ('a.txt', False, 5)}


def test_list_dir_on_file_raises(backend: MemoryBackend):
    put(backend, '/a.txt')
    with pytest.raises(NotADirectoryError):
        for _ in backend.list_dir(P('/a.txt')):
            pass


def test_list_dir_missing_raises(backend: MemoryBackend):
    with pytest.raises(PathNotFoundError):
        for _ in backend.list_dir(P('/nope')):
            pass


def test_list_dir_tolerates_delete_during_iteration(backend: MemoryBackend):
    backend.make_dir(P('/d'), parents=False)
    for name in ('a', 'b', 'c'):
        put(backend, f'/d/{name}')

    for entry in backend.list_dir(P('/d')):
        backend.delete(P('/d') / entry.name)

    assert list(backend.list_dir(P('/d'))) == []


# --- stat ---


def test_stat_file(backend: MemoryBackend):
    put(backend, '/a.txt', b'12345')
    props = backend.stat(P('/a.txt'))
    assert props.kind == 'file'
    assert props.size == 5
    assert props.created.tzinfo is not None
    assert props.modified.tzinfo is not None


def test_stat_directory_size_is_zero(backend: MemoryBackend):
    backend.make_dir(P('/d'), parents=False)
    put(backend, '/d/a.txt', b'12345')
    props = backend.stat(P('/d'))
    assert props.kind == 'directory'
    assert props.size == 0


def test_append_updates_modified_preserves_created(backend: MemoryBackend):
    put(backend, '/a.txt', b'x')
    before = backend.stat(P('/a.txt'))
    put(backend, '/a.txt', b'y', mode='a')
    after = backend.stat(P('/a.txt'))
    assert after.created == before.created
    assert after.modified >= before.modified


# --- make_dir ---


def test_make_dir_plain(backend: MemoryBackend):
    backend.make_dir(P('/d'), parents=False)
    assert (backend.stat(P('/d'))).kind == 'directory'


def test_make_dir_missing_parent_raises(backend: MemoryBackend):
    with pytest.raises(PathNotFoundError) as excinfo:
        backend.make_dir(P('/missing/d'), parents=False)
    assert str(excinfo.value.path) == '/missing'


def test_make_dir_parent_is_file_raises(backend: MemoryBackend):
    put(backend, '/a.txt')
    with pytest.raises(NotADirectoryError):
        backend.make_dir(P('/a.txt/d'), parents=False)


def test_make_dir_existing_raises(backend: MemoryBackend):
    backend.make_dir(P('/d'), parents=False)
    with pytest.raises(AlreadyExistsError):
        backend.make_dir(P('/d'), parents=False)


def test_make_dir_parents_creates_chain(backend: MemoryBackend):
    backend.make_dir(P('/a/b/c'), parents=True)
    for path in ('/a', '/a/b', '/a/b/c'):
        assert (backend.stat(P(path))).kind == 'directory'


def test_make_dir_parents_is_idempotent(backend: MemoryBackend):
    backend.make_dir(P('/d'), parents=True)
    backend.make_dir(P('/d'), parents=True)  # no raise


def test_make_dir_parents_existing_file_still_raises(backend: MemoryBackend):
    put(backend, '/a.txt')
    with pytest.raises(AlreadyExistsError):
        backend.make_dir(P('/a.txt'), parents=True)


def test_make_dir_parents_file_in_chain_raises(backend: MemoryBackend):
    put(backend, '/a.txt')
    with pytest.raises(NotADirectoryError):
        backend.make_dir(P('/a.txt/d'), parents=True)


# --- delete ---


def test_delete_file(backend: MemoryBackend):
    put(backend, '/a.txt')
    backend.delete(P('/a.txt'))
    assert not backend.exists(P('/a.txt'))


def test_delete_empty_directory(backend: MemoryBackend):
    backend.make_dir(P('/d'), parents=False)
    backend.delete(P('/d'))
    assert not backend.exists(P('/d'))


def test_delete_non_empty_directory_raises(backend: MemoryBackend):
    backend.make_dir(P('/d'), parents=False)
    put(backend, '/d/a.txt')
    with pytest.raises(DirectoryNotEmptyError):
        backend.delete(P('/d'))


def test_delete_missing_raises(backend: MemoryBackend):
    with pytest.raises(PathNotFoundError):
        backend.delete(P('/nope'))


# --- generic fallbacks through BackendBase ---


def test_du_file(backend: MemoryBackend):
    put(backend, '/a.txt', b'12345')
    assert backend.du(P('/a.txt')) == 5


def test_du_sums_tree(backend: MemoryBackend):
    backend.make_dir(P('/a/b'), parents=True)
    put(backend, '/a/f1', b'123')
    put(backend, '/a/b/f2', b'12345')
    assert backend.du(P('/a')) == 8
    assert backend.du(P('/')) == 8


def test_move_file(backend: MemoryBackend):
    put(backend, '/src.txt', b'payload')
    backend.move(P('/src.txt'), P('/dst.txt'))
    assert backend.read(P('/dst.txt')) == b'payload'
    assert not backend.exists(P('/src.txt'))


def test_copy_file_is_independent(backend: MemoryBackend):
    put(backend, '/src.txt', b'payload')
    backend.copy(P('/src.txt'), P('/dst.txt'))
    assert backend.read(P('/dst.txt')) == b'payload'

    # mutating the copy must not touch the original (no buffer aliasing)
    put(backend, '/dst.txt', b' more', mode='a')
    assert backend.read(P('/src.txt')) == b'payload'


def test_delete_tree_removes_everything(backend: MemoryBackend):
    backend.make_dir(P('/d/sub'), parents=True)
    put(backend, '/d/a.txt', b'x')
    put(backend, '/d/sub/b.txt', b'y')

    backend.delete_tree(P('/d'))

    for path in ('/d', '/d/sub', '/d/a.txt', '/d/sub/b.txt'):
        assert not backend.exists(P(path))
    assert backend.exists(P('/'))
