# DO NOT EDIT - GENERATED by scripts/unasync.py
# source of truth: tests/_async/backends/test_memory.py
"""Memory-backend specifics; shared behavior lives in test_backends.py."""

from collections.abc import Iterator
from pathlib import PurePosixPath as P

import pytest

from storix._sync.backends import BackendBase, StorageBackend
from storix._sync.backends.memory import MemoryBackend
from storix.types import EchoMode


def _astream(*chunks: bytes) -> Iterator[bytes]:
    yield from chunks


def put(
    backend: MemoryBackend, path: str, data: bytes = b'', mode: EchoMode = 'w'
) -> None:
    backend.write(P(path), _astream(data), mode=mode, content_type=None)


def test_backendbase_is_abstract():
    with pytest.raises(TypeError):
        BackendBase()  # type: ignore[abstract]


def test_memory_satisfies_protocol():
    # the annotation is the test: type checkers verify structural conformance
    backend: StorageBackend = MemoryBackend()
    assert backend.capabilities.content_type is False


def test_append_updates_modified_preserves_created():
    """Memory-specific: POSIX ctime shifts on append, so only the memory
    backend can promise creation-time stability across appends.
    """
    backend = MemoryBackend()
    put(backend, '/a.txt', b'x')
    before = backend.stat(P('/a.txt'))
    put(backend, '/a.txt', b'y', mode='a')
    after = backend.stat(P('/a.txt'))
    assert after.created == before.created
    assert after.modified >= before.modified
