# DO NOT EDIT - GENERATED by scripts/unasync.py
# source of truth: tests/_async/backends/test_backends.py
# ruff: noqa: A004
"""The backend conformance suite: one behavior spec, every backend.

Every StorageBackend implementation must pass every test here - this is
the enforcement mechanism for 'one behavior everywhere'. Backend-specific
quirks live in the per-backend test files.
"""

import os
import uuid

from collections.abc import Iterator
from pathlib import Path, PurePosixPath as P

import pytest

from storix._sync.backends import StorageBackend
from storix._sync.backends.local import LocalBackend
from storix._sync.backends.memory import MemoryBackend
from storix._sync.layers import SandboxLayer
from storix.errors import (
    AlreadyExistsError,
    DirectoryNotEmptyError,
    IsADirectoryError,
    NotADirectoryError,
    PathNotFoundError,
    UnsupportedOperationError,
)
from storix.types import EchoMode


@pytest.fixture(
    params=[
        'memory',
        'local',
        'sandbox',
        pytest.param('azure', marks=pytest.mark.integration),
    ]
)
def backend(request: pytest.FixtureRequest, tmp_path: Path) -> Iterator[StorageBackend]:
    if request.param == 'memory':
        yield MemoryBackend()
        return
    if request.param == 'local':
        yield LocalBackend(tmp_path)
        return
    if request.param == 'sandbox':
        # a layer must satisfy the full port contract like any backend
        inner = MemoryBackend()
        inner.make_dir(P('/jail'), parents=False)
        yield SandboxLayer(inner, root='/jail')
        return

    account = os.environ.get('ADLSG2_ACCOUNT_NAME')
    token = os.environ.get('ADLSG2_TOKEN')
    if not (account and token):
        pytest.skip('azure integration credentials not configured')
    from storix._sync.backends.azure import AzureBackend

    azure = AzureBackend(
        f'storix-conformance-{uuid.uuid4().hex[:12]}',
        account_name=account,
        credential=token,
    )
    azure._filesystem.create_file_system()
    try:
        yield azure
    finally:
        azure._filesystem.delete_file_system()
        azure.close()


def _astream(*chunks: bytes) -> Iterator[bytes]:
    yield from chunks


def put(
    backend: StorageBackend, path: str, data: bytes = b'', mode: EchoMode = 'w'
) -> None:
    backend.write(P(path), _astream(data), mode=mode, content_type=None)


def test_root_exists_initially(backend: StorageBackend):
    assert backend.exists(P('/'))
    assert not backend.exists(P('/anything'))


# --- write / read ---


def test_write_creates_and_read_round_trips(backend: StorageBackend):
    put(backend, '/a.txt', b'hello')
    assert backend.read(P('/a.txt')) == b'hello'


def test_write_truncates_existing(backend: StorageBackend):
    put(backend, '/a.txt', b'old content')
    put(backend, '/a.txt', b'new')
    assert backend.read(P('/a.txt')) == b'new'


def test_append_extends(backend: StorageBackend):
    put(backend, '/a.txt', b'hello ')
    put(backend, '/a.txt', b'world', mode='a')
    assert backend.read(P('/a.txt')) == b'hello world'


def test_append_creates_missing(backend: StorageBackend):
    put(backend, '/a.txt', b'created', mode='a')
    assert backend.read(P('/a.txt')) == b'created'


@pytest.mark.parametrize('mode', ['w', 'a'])
def test_write_onto_directory_raises(backend: StorageBackend, mode: EchoMode):
    backend.make_dir(P('/d'), parents=False)
    with pytest.raises(IsADirectoryError):
        put(backend, '/d', b'x', mode=mode)


def test_read_missing_raises(backend: StorageBackend):
    with pytest.raises(PathNotFoundError):
        backend.read(P('/nope'))


def test_read_directory_raises(backend: StorageBackend):
    backend.make_dir(P('/d'), parents=False)
    with pytest.raises(IsADirectoryError):
        backend.read(P('/d'))


def test_read_stream_yields_content(backend: StorageBackend):
    put(backend, '/a.txt', b'streamed')
    chunks = list(backend.read_stream(P('/a.txt')))
    assert b''.join(chunks) == b'streamed'


# --- list_dir ---


def test_list_dir_entries(backend: StorageBackend):
    backend.make_dir(P('/d'), parents=False)
    backend.make_dir(P('/d/sub'), parents=False)
    put(backend, '/d/a.txt', b'12345')

    entries = {(e.name, e.is_dir, e.size) for e in backend.list_dir(P('/d'))}
    # directory entries report size=None: a listing size is only meaningful
    # for files, and du() recurses into directories regardless
    assert entries == {('sub', True, None), ('a.txt', False, 5)}


def test_list_dir_on_file_raises(backend: StorageBackend):
    put(backend, '/a.txt')
    with pytest.raises(NotADirectoryError):
        for _ in backend.list_dir(P('/a.txt')):
            pass


def test_list_dir_missing_raises(backend: StorageBackend):
    with pytest.raises(PathNotFoundError):
        for _ in backend.list_dir(P('/nope')):
            pass


def test_list_dir_tolerates_delete_during_iteration(backend: StorageBackend):
    backend.make_dir(P('/d'), parents=False)
    for name in ('a', 'b', 'c'):
        put(backend, f'/d/{name}')

    for entry in backend.list_dir(P('/d')):
        backend.delete(P('/d') / entry.name)

    assert list(backend.list_dir(P('/d'))) == []


# --- stat ---


def test_stat_file(backend: StorageBackend):
    put(backend, '/a.txt', b'12345')
    props = backend.stat(P('/a.txt'))
    assert props.kind == 'file'
    assert props.size == 5
    assert props.created.tzinfo is not None
    assert props.modified.tzinfo is not None


def test_stat_directory_size_is_zero(backend: StorageBackend):
    backend.make_dir(P('/d'), parents=False)
    put(backend, '/d/a.txt', b'12345')
    props = backend.stat(P('/d'))
    assert props.kind == 'directory'
    assert props.size == 0


def test_metadata_round_trip(backend: StorageBackend):
    if not backend.capabilities.custom_metadata:
        pytest.skip('backend does not advertise custom_metadata')
    backend.write(
        P('/m.txt'),
        _astream(b'x'),
        mode='w',
        content_type=None,
        metadata={'owner': 'tests'},
    )
    raw = backend.stat(P('/m.txt'))
    assert raw.metadata == {'owner': 'tests'}


def test_metadata_absent_by_default(backend: StorageBackend):
    put(backend, '/plain.txt', b'x')
    assert (backend.stat(P('/plain.txt'))).metadata is None


def test_metadata_replace_semantics(backend: StorageBackend):
    """Provided mapping replaces; None preserves on append; {} clears."""
    if not backend.capabilities.custom_metadata:
        pytest.skip('backend does not advertise custom_metadata')

    def put_meta(data: bytes, mode: EchoMode, metadata: dict | None) -> None:
        backend.write(
            P('/m.txt'), _astream(data), mode=mode, content_type=None, metadata=metadata
        )

    def meta() -> dict | None:
        raw = backend.stat(P('/m.txt'))
        return dict(raw.metadata) if raw.metadata is not None else None

    put_meta(b'x', 'w', {'a': '1', 'b': '2'})
    put_meta(b'y', 'a', None)  # None preserves on append
    assert meta() == {'a': '1', 'b': '2'}

    put_meta(b'z', 'a', {'c': '3'})  # replace, not merge
    assert meta() == {'c': '3'}

    put_meta(b'w', 'a', {})  # empty mapping clears
    assert meta() is None


def test_make_url_respects_capability(backend: StorageBackend):
    put(backend, '/u.txt', b'x')
    if backend.capabilities.presigned_urls:
        url = backend.make_url(P('/u.txt'), expires_in=60)
        assert url.startswith('https://')
    else:
        with pytest.raises(UnsupportedOperationError):
            backend.make_url(P('/u.txt'), expires_in=60)


def test_append_updates_modified(backend: StorageBackend):
    put(backend, '/a.txt', b'x')
    before = backend.stat(P('/a.txt'))
    put(backend, '/a.txt', b'y', mode='a')
    after = backend.stat(P('/a.txt'))
    assert after.modified >= before.modified


# --- make_dir ---


def test_make_dir_plain(backend: StorageBackend):
    backend.make_dir(P('/d'), parents=False)
    assert (backend.stat(P('/d'))).kind == 'directory'


def test_make_dir_missing_parent_raises(backend: StorageBackend):
    with pytest.raises(PathNotFoundError) as excinfo:
        backend.make_dir(P('/missing/d'), parents=False)
    assert str(excinfo.value.path) == '/missing'


def test_make_dir_parent_is_file_raises(backend: StorageBackend):
    put(backend, '/a.txt')
    with pytest.raises(NotADirectoryError):
        backend.make_dir(P('/a.txt/d'), parents=False)


def test_make_dir_existing_raises(backend: StorageBackend):
    backend.make_dir(P('/d'), parents=False)
    with pytest.raises(AlreadyExistsError):
        backend.make_dir(P('/d'), parents=False)


def test_make_dir_parents_creates_chain(backend: StorageBackend):
    backend.make_dir(P('/a/b/c'), parents=True)
    for path in ('/a', '/a/b', '/a/b/c'):
        assert (backend.stat(P(path))).kind == 'directory'


def test_make_dir_parents_is_idempotent(backend: StorageBackend):
    backend.make_dir(P('/d'), parents=True)
    backend.make_dir(P('/d'), parents=True)  # no raise


def test_make_dir_parents_existing_file_still_raises(backend: StorageBackend):
    put(backend, '/a.txt')
    with pytest.raises(AlreadyExistsError):
        backend.make_dir(P('/a.txt'), parents=True)


# --- delete ---


def test_delete_file(backend: StorageBackend):
    put(backend, '/a.txt')
    backend.delete(P('/a.txt'))
    assert not backend.exists(P('/a.txt'))


def test_delete_empty_directory(backend: StorageBackend):
    backend.make_dir(P('/d'), parents=False)
    backend.delete(P('/d'))
    assert not backend.exists(P('/d'))


def test_delete_non_empty_directory_raises(backend: StorageBackend):
    backend.make_dir(P('/d'), parents=False)
    put(backend, '/d/a.txt')
    with pytest.raises(DirectoryNotEmptyError):
        backend.delete(P('/d'))


def test_delete_missing_raises(backend: StorageBackend):
    with pytest.raises(PathNotFoundError):
        backend.delete(P('/nope'))


# --- generic fallbacks / native fast paths through the same contract ---


def test_du_file(backend: StorageBackend):
    put(backend, '/a.txt', b'12345')
    assert backend.du(P('/a.txt')) == 5


def test_du_sums_tree(backend: StorageBackend):
    backend.make_dir(P('/a/b'), parents=True)
    put(backend, '/a/f1', b'123')
    put(backend, '/a/b/f2', b'12345')
    assert backend.du(P('/a')) == 8
    assert backend.du(P('/')) == 8


def test_move_file(backend: StorageBackend):
    put(backend, '/src.txt', b'payload')
    backend.move(P('/src.txt'), P('/dst.txt'))
    assert backend.read(P('/dst.txt')) == b'payload'
    assert not backend.exists(P('/src.txt'))


def test_move_directory_tree(backend: StorageBackend):
    backend.make_dir(P('/d/sub'), parents=True)
    put(backend, '/d/sub/a.txt', b'x')
    backend.move(P('/d'), P('/renamed'))
    assert backend.read(P('/renamed/sub/a.txt')) == b'x'
    assert not backend.exists(P('/d'))


def test_copy_file_is_independent(backend: StorageBackend):
    put(backend, '/src.txt', b'payload')
    backend.copy(P('/src.txt'), P('/dst.txt'))
    assert backend.read(P('/dst.txt')) == b'payload'

    # mutating the copy must not touch the original (no buffer aliasing)
    put(backend, '/dst.txt', b' more', mode='a')
    assert backend.read(P('/src.txt')) == b'payload'


def test_delete_tree_removes_everything(backend: StorageBackend):
    backend.make_dir(P('/d/sub'), parents=True)
    put(backend, '/d/a.txt', b'x')
    put(backend, '/d/sub/b.txt', b'y')

    backend.delete_tree(P('/d'))

    for path in ('/d', '/d/sub', '/d/a.txt', '/d/sub/b.txt'):
        assert not backend.exists(P(path))
    assert backend.exists(P('/'))
