# DO NOT EDIT - GENERATED by scripts/unasync.py
# source of truth: src/storix/_async/_stream.py
"""Byte-stream helpers for the backends and core."""

from collections.abc import Buffer, Iterator

from storix.constants import DEFAULT_WRITE_CHUNKSIZE


def collect(stream: Iterator[bytes]) -> bytes:
    """Drain a chunk stream into a single bytes object."""
    return b''.join(list(stream))


def chunked(data: Buffer, size: int = DEFAULT_WRITE_CHUNKSIZE) -> Iterator[bytes]:
    """Slice any buffer into ``bytes`` chunks with a single copy per chunk.

    The ``memoryview`` makes slicing zero-copy regardless of the input
    buffer type; ``bytes()`` performs the one copy consumers need.
    """
    view = memoryview(data)

    for i in range(0, len(view), size):
        yield bytes(view[i : i + size])
