# DO NOT EDIT - GENERATED by scripts/unasync.py
# source of truth: src/storix/_async/core.py
"""The unix-flavored engine: one stateful session over any storage backend."""
# ruff: noqa: A004 - storix error classes intentionally shadow stdlib names

from __future__ import annotations

import copy

from typing import TYPE_CHECKING, Any, ParamSpec, Protocol, Self, cast

from storix import pathops
from storix._sync._compat import gather
from storix._sync._stream import ensure_chunks, validate_chunk_size
from storix._sync.backends import generic
from storix.enums import Capability, PathKind
from storix.errors import (
    IsADirectoryError,
    NonRemovableLayerError,
    NotADirectoryError,
    PathNotFoundError,
    UnsupportedOperationError,
)
from storix.models import FileProperties
from storix.types import StorixPath


if TYPE_CHECKING:
    from collections.abc import Callable, Iterable, Iterator, Mapping
    from contextlib import AbstractContextManager

    from storix._sync.backends import StorageBackend
    from storix.types import DataBuffer, EchoMode, StrPathLike


P = ParamSpec('P')


class LayerFactory(Protocol[P]):
    """A layer class/factory: backend first, then its own params.

    Public so integrators writing their own layer helpers can name the
    type; it appears in the ``when_missing`` signature.
    """

    def __call__(
        self, backend: StorageBackend, /, *args: P.args, **kwargs: P.kwargs
    ) -> StorageBackend: ...


# a fully-bound layer (the layers= list, and what with_layer produces):
# backend in, backend out. Public so consumers need not redefine it.
type BoundLayer = Callable[[StorageBackend], StorageBackend]


_ROOT = StorixPath('/')


class Storix:
    """A unix-flavored filesystem session over a storage backend.

    One instance is one stateful session (cwd, home) over one backend.
    Every user-supplied path funnels through ``pathops.resolve`` (cwd,
    ``~``, ``..``) before reaching the port, and every failure raises a
    typed ``storix.errors`` exception - no boolean error returns.

    ``home`` is resolved lexically at construction but neither validated
    nor created; the first operation against a missing home fails with
    ``PathNotFoundError`` like any other path would.
    """

    def __init__(
        self,
        backend: StorageBackend,
        *,
        home: StrPathLike = '/',
        layers: Iterable[BoundLayer] = (),
    ) -> None:
        """Open a session over ``backend``, optionally stacking layers.

        ``layers`` are factories taking a backend and returning a wrapped
        one (a layer class taking only the backend, or a
        ``functools.partial`` carrying its options). Applied in order:
        each wraps the previous, so the *last* entry is outermost.
        """
        for build in layers:
            backend = build(backend)
        self._backend = backend
        self._home = pathops.resolve(home, cwd=_ROOT, home=_ROOT)
        self._cwd = self._home

    # --- identity ---

    @property
    def backend(self) -> StorageBackend:
        """Escape hatch: the raw port for backend-specific operations."""
        return self._backend

    @property
    def root(self) -> StorixPath:
        """The filesystem root (always ``/``)."""
        return _ROOT

    @property
    def home(self) -> StorixPath:
        """The session's home directory (the ``~`` anchor)."""
        return self._home

    def pwd(self) -> StorixPath:
        """Return the current working directory."""
        return self._cwd

    # --- lifecycle ---

    def close(self) -> None:
        """Release the backend's resources (idempotent)."""
        self._backend.close()

    def __enter__(self) -> Self:
        return self

    def __exit__(self, *_: object) -> None:
        self.close()

    def chroot(self, path: StrPathLike, /) -> Self:
        """Return a *new* session whose root is ``path`` (resolved here).

        Sugar for wrapping this session's backend in a ``SandboxLayer`` -
        the new session cannot see or escape above ``path``, and errors
        inside it are re-scoped to its namespace. The current session is
        untouched. Keep an explicit ``SandboxLayer`` instead when you
        need the privileged ``to_real``/``to_virtual`` handle (audit).
        """
        from .layers import SandboxLayer

        return type(self)(SandboxLayer(self._backend, root=self._resolve(path)))

    def with_layer(
        self, layer: LayerFactory[P], /, *args: P.args, **kwargs: P.kwargs
    ) -> Self:
        """Return a *new* session over this backend wrapped in ``layer``.

        Strongly-typed forwarder (Starlette ``add_middleware`` style):
        extra args/kwargs go to the layer's constructor and are checked
        against its signature::

            fs.with_layer(MetadataLayer, serialize=orjson.dumps)

        The current session is untouched; the new one starts at its home
        (a live cwd may not exist inside the new namespace). For
        native-preference use ``with_layer_missing``.
        """
        return type(self)(layer(self._backend, *args, **kwargs), home=self._home)

    def with_layer_missing(
        self, layer: LayerFactory[P], /, *args: P.args, **kwargs: P.kwargs
    ) -> Self:
        """Like ``with_layer``, but skip it when the backend is already native.

        Native-preference with the capability *inferred* from the layer's
        ``provides`` - no redundant capability argument. One construction
        path spans providers (Azure's native SAS wins, the layer no-ops)::

            fs.with_layer_missing(DataUrlLayer)  # provides PRESIGNED_URLS
            fs.with_layer_missing(MetadataLayer)  # provides CUSTOM_METADATA

        Returns the current session unchanged when the capability is
        native. Raises ``ValueError`` if the layer declares no
        ``provides`` (nothing to infer - use ``with_layer``).
        """
        from .layers.native import when_missing

        wrapped = when_missing(layer, *args, **kwargs)(self._backend)
        if wrapped is self._backend:  # native: skipped, no new session
            return self
        return type(self)(wrapped, home=self._home)

    def without_layer(self, *layers: type) -> Self:
        """Return a *new* session with the given layer types bypassed.

        Walks the stack and drops every layer that is an instance of one of
        ``layers``, re-composing the rest so operations go straight past
        them - e.g. ``fs.without_layer(CacheLayer).ls()`` forces a
        cache-bypassing read. Layer types not present are a no-op, so this
        is safe to call unconditionally. The current session is untouched;
        cwd is preserved (a removable layer never changes the path
        namespace).

        Raises :class:`~storix.errors.NonRemovableLayerError` if a matched
        layer sets ``removable = False`` - a :class:`SandboxLayer` is a
        security boundary and can never be stripped.
        """
        chain: list[StorageBackend] = []
        node = self._backend
        while (inner := getattr(node, '_inner', None)) is not None:
            chain.append(node)
            node = inner
        for lyr in chain:
            if isinstance(lyr, layers) and not getattr(lyr, 'removable', True):
                raise NonRemovableLayerError(type(lyr).__name__)
        rebuilt = node  # the base backend
        for lyr in reversed(chain):
            if isinstance(lyr, layers):
                continue
            # shallow copy: only the wrapped backend changes. The chain walk
            # is duck-typed on '_inner', so the port type cannot carry the
            # attribute; Any reflects that honestly.
            clone = cast('Any', copy.copy(lyr))
            clone._inner = rebuilt  # noqa: SLF001 - core owns layer re-composition
            rebuilt = clone
        new = type(self)(rebuilt, home=self._home)
        new._cwd = self._cwd  # noqa: SLF001 - carry cwd (same namespace, same class)
        return new

    @property
    def uncached(self) -> Self:
        """This session with any ``CacheLayer`` bypassed (a fresh-read view).

        Sugar for ``without_layer(CacheLayer)``; a no-op when no cache is
        active. Use for a guaranteed-fresh read: ``fs.uncached.ls()``.
        """
        from .layers import CacheLayer

        return self.without_layer(CacheLayer)

    def scratch(
        self, *, root: StrPathLike | None = None, prefix: str = 'scratch-'
    ) -> AbstractContextManager[Storix]:
        """Ephemeral (or pinned) workspace on this session's own backend.

        Sugar for ``storix.scratch(fs.backend, ...)``; see it for the
        pin-vs-dispose semantics.
        """
        from .temporary import scratch

        return scratch(self._backend, root=root, prefix=prefix)

    # --- resolution ---

    def _resolve(self, path: StrPathLike | None = None) -> StorixPath:
        """Funnel every user path through the lexical pipeline."""
        if path is None:
            return self._cwd
        return pathops.resolve(path, cwd=self._cwd, home=self._home)

    def resolve(self, path: StrPathLike | None = None) -> StorixPath:
        """Absolute session path for ``path`` (cwd/``~``/``..`` applied).

        This is the **navigable, bookmarkable** form - a plain port path
        you can hand back to ``cd``/``cat``/anything::

            here = fs.resolve()  # '/raw/videos'
            fs.cd('/tmp')
            fs.cd(here)  # back to the bookmark

        Stable within a session (and across sessions built the same way).
        For an *external* reference to the object, use ``locate``.
        """
        return self._resolve(path)

    def locate(self, path: StrPathLike | None = None) -> str:
        """Fully-qualified physical locator for a path - a URI.

        For *external* reference (audit records, logs, other tools):
        where the path actually lives, resolved through any sandbox to
        the real backend location (``file:///srv/data/x``,
        ``abfss://c@acct.dfs...net/x``).

        Not a port path - you cannot ``cd`` to it (and by design a
        sandboxed session must not navigate to a real path above its
        root). To navigate, use ``resolve``; to rebuild a session *from*
        a locator, the URI factory (roadmap 0.3.0).
        """
        return self._backend.locate(self._resolve(path))

    def _ensure_parent(self, path: StorixPath) -> None:
        """Raise unless ``path``'s parent exists and is a directory."""
        parent = path.parent
        raw = self._backend.stat(parent)
        if raw.kind is not PathKind.DIRECTORY:
            raise NotADirectoryError(parent)

    def _ensure_capability(self, capability: Capability) -> None:
        """Raise unless the backend advertises the capability."""
        if not self._backend.capabilities.supports(capability):
            raise UnsupportedOperationError(capability)

    # --- navigation ---

    def cd(self, path: StrPathLike | None = None) -> Self:
        """Change the working directory; no argument returns home."""
        target = self._home if path is None else self._resolve(path)
        raw = self._backend.stat(target)
        if raw.kind is not PathKind.DIRECTORY:
            raise NotADirectoryError(target)
        self._cwd = target
        return self

    # --- read ---

    def ls(
        self,
        path: StrPathLike | None = None,
        *,
        all: bool = False,
        abs: bool = False,
    ) -> list[StorixPath]:
        """List a directory (hidden entries excluded unless ``all=True``).

        Like unix ls, listing a file returns the file itself.
        """
        target = self._resolve(path)
        raw = self._backend.stat(target)
        if raw.kind is PathKind.FILE:
            return [target if abs else StorixPath(target.name)]

        names = [entry.name for entry in self._backend.list_dir(target)]
        if not all:
            names = [name for name in names if not pathops.is_hidden(name)]
        if abs:
            return [target / name for name in names]
        return [StorixPath(name) for name in names]

    def cat(self, path: StrPathLike, /, *paths: StrPathLike) -> bytes:
        """Read one or more files, concatenated in argument order."""
        targets = [self._resolve(p) for p in (path, *paths)]
        parts = gather(*(self._backend.read(target) for target in targets))
        return b''.join(parts)

    def stream(
        self,
        path: StrPathLike,
        /,
        *paths: StrPathLike,
        chunk_size: int | None = None,
    ) -> Iterator[bytes]:
        """Stream file contents in chunks - the streaming form of ``cat``.

        Multiple paths concatenate in order, chunk by chunk. Streaming-native
        backends use bounded memory however large the files; a whole-object
        backend fallback may materialize a file before splitting it. Feeds
        straight into e.g. FastAPI's ``StreamingResponse``. Range reads
        (``head -c``/seek) are a planned port extension.

        Args:
            path: The first (or only) file to stream.
            paths: Further files, concatenated after ``path`` in order.
            chunk_size: Maximum yielded chunk size. ``None`` selects each
                backend's preferred default. Smaller native chunks may pass
                through unchanged; chunk boundaries carry no meaning.

        Raises:
            ValueError: If ``chunk_size`` is zero or negative.
            PathNotFoundError: If any requested path does not exist.
            IsADirectoryError: If any requested path is a directory.
        """
        validate_chunk_size(chunk_size)
        for target in [self._resolve(p) for p in (path, *paths)]:
            yield from self._backend.read_stream(target, chunk_size=chunk_size)

    def stat(self, path: StrPathLike | None = None) -> FileProperties:
        """Return the user-facing properties of a path."""
        target = self._resolve(path)
        raw = self._backend.stat(target)
        return FileProperties.from_raw(target.name or '/', raw)

    def set_metadata(
        self,
        path: StrPathLike,
        metadata: Mapping[str, str],
        /,
        *,
        merge: bool = False,
    ) -> None:
        """Replace (default) or merge a file's custom metadata.

        Replace costs one backend request; ``merge=True`` stats first
        (read-merge-write - not atomic under concurrent writers).
        Requires ``capabilities.custom_metadata``.
        """
        self._ensure_capability(Capability.CUSTOM_METADATA)
        target = self._resolve(path)
        payload = dict(metadata)
        if merge:
            existing = (self._backend.stat(target)).metadata or {}
            payload = {**existing, **payload}
        self._backend.set_metadata(target, payload)

    def url(
        self,
        path: StrPathLike | None = None,
        *,
        expires_in: int | None = None,
    ) -> str:
        """Mint a shareable URL for a file (Azure: a SAS URL).

        Requires ``capabilities.presigned_urls``. ``expires_in`` is
        advisory: ``None`` means the provider's default lifetime, and
        providers without expiring links ignore it.
        """
        self._ensure_capability(Capability.PRESIGNED_URLS)
        return self._backend.make_url(self._resolve(path), expires_in=expires_in)

    def data_url(self, path: StrPathLike | None = None) -> str:
        """Return the file inlined as a base64 ``data:`` URL (any backend)."""
        from storix.utils import to_data_url

        return to_data_url(buf=self._backend.read(self._resolve(path)))

    def du(self, path: StrPathLike | None = None) -> int:
        """Total *content* size in bytes of the tree rooted at ``path``.

        Apparent bytes, like ``du -sb`` on files: the sum of file sizes.
        GNU du's default output differs by design - it counts allocated
        filesystem blocks and directory entries, concepts that do not
        exist on object stores.
        """
        return self._backend.du(self._resolve(path))

    def exists(self, path: StrPathLike | None = None) -> bool:
        """Whether anything lives at ``path``."""
        return self._backend.exists(self._resolve(path))

    def isfile(self, path: StrPathLike | None = None) -> bool:
        """Whether ``path`` is a file (False when missing, like ``test -f``)."""
        try:
            raw = self._backend.stat(self._resolve(path))
        except PathNotFoundError:
            return False
        return raw.kind is PathKind.FILE

    def isdir(self, path: StrPathLike | None = None) -> bool:
        """Whether ``path`` is a directory (False when missing)."""
        try:
            raw = self._backend.stat(self._resolve(path))
        except PathNotFoundError:
            return False
        return raw.kind is PathKind.DIRECTORY

    # --- write ---

    def touch(self, path: StrPathLike, /, *paths: StrPathLike) -> None:
        """Create files if missing; refresh mtime of existing files.

        Unlike unix touch, directories are rejected (``IsADirectoryError``)
        - storage backends cannot bump a directory's mtime portably.
        """
        targets = [self._resolve(p) for p in (path, *paths)]
        for target in targets:
            self._ensure_parent(target)
        gather(
            *(
                self._backend.write(target, b'', mode='a', content_type=None)
                for target in targets
            )
        )

    def echo(
        self,
        data: DataBuffer[str] | DataBuffer[bytes],
        path: StrPathLike,
        /,
        *,
        chunk_size: int | None = None,
        mode: EchoMode = 'w',
        content_type: str | None = None,
        metadata: Mapping[str, str] | None = None,
    ) -> None:
        """Write data into a file, creating it if missing.

        ``mode='w'`` truncates, ``mode='a'`` appends. Accepts str/bytes,
        readable file-like objects, and (async) iterables of either. Source
        boundaries are normalized into efficient backend write batches.
        ``content_type`` and ``metadata`` require the matching backend
        capability.

        Args:
            data: Complete contents or a lazy source producing them.
            path: Destination file.
            chunk_size: Maximum target write-batch size. ``None`` selects the
                backend's preferred default.
            mode: ``'w'`` to replace or ``'a'`` to append.
            content_type: Optional media type for capable backends.
            metadata: Optional replacement metadata for capable backends.

        Raises:
            ValueError: If ``chunk_size`` is zero or negative.
            UnsupportedOperationError: If requested metadata or content type
                is not supported by the backend stack.
            PathNotFoundError: If the destination parent does not exist.
            IsADirectoryError: If the destination is a directory.
        """
        validate_chunk_size(chunk_size)
        if content_type is not None:
            self._ensure_capability(Capability.CONTENT_TYPE)
        if metadata is not None:
            self._ensure_capability(Capability.CUSTOM_METADATA)
        target = self._resolve(path)
        self._ensure_parent(target)
        self._backend.write_stream(
            target,
            ensure_chunks(data),
            chunk_size=chunk_size,
            mode=mode,
            content_type=content_type,
            metadata=metadata,
        )

    def mkdir(
        self, path: StrPathLike, /, *paths: StrPathLike, parents: bool = False
    ) -> None:
        """Create directories.

        ``parents=True`` is ``mkdir -p`` with both of its unix meanings:
        missing ancestors are created *and* an already-existing directory
        is a silent success (an existing file still raises). Plain mkdir
        raises ``AlreadyExistsError`` on any existing target.
        """
        targets = [self._resolve(p) for p in (path, *paths)]
        gather(*(self._backend.make_dir(target, parents=parents) for target in targets))

    # --- delete ---

    def rm(
        self, path: StrPathLike, /, *paths: StrPathLike, recursive: bool = False
    ) -> None:
        """Delete files; with ``recursive=True`` (rm -r) also directories.

        All targets are validated before anything is deleted.
        """
        targets = [self._resolve(p) for p in (path, *paths)]
        stats = gather(*(self._backend.stat(target) for target in targets))
        for target, raw in zip(targets, stats, strict=True):
            if raw.kind is PathKind.DIRECTORY and not recursive:
                raise IsADirectoryError(target)
        gather(
            *(
                self._backend.delete_tree(target)
                if raw.kind is PathKind.DIRECTORY
                else self._backend.delete(target)
                for target, raw in zip(targets, stats, strict=True)
            )
        )

    def rmdir(self, path: StrPathLike, /, *paths: StrPathLike) -> None:
        """Delete empty directories - strict unix rmdir.

        A non-empty directory raises ``DirectoryNotEmptyError`` (use
        ``rm(recursive=True)`` for trees); a file raises
        ``NotADirectoryError``.
        """
        targets = [self._resolve(p) for p in (path, *paths)]
        stats = gather(*(self._backend.stat(target) for target in targets))
        for target, raw in zip(targets, stats, strict=True):
            if raw.kind is not PathKind.DIRECTORY:
                raise NotADirectoryError(target)
        gather(*(self._backend.delete(target) for target in targets))

    # --- move / copy ---

    def mv(self, source: StrPathLike, /, *paths: StrPathLike) -> None:
        """Move/rename; the last argument is the destination (unix mv).

        A single source renames onto the destination (or moves *into* it
        when it is an existing directory); multiple sources require an
        existing directory destination.
        """
        sources, dst = self._split_destination('mv', source, paths)
        targets = self._plan_destinations(sources, dst)
        gather(
            *(
                self._backend.move(src, target)
                for src, target in zip(sources, targets, strict=True)
            )
        )

    def cp(
        self, source: StrPathLike, /, *paths: StrPathLike, recursive: bool = False
    ) -> None:
        """Copy; the last argument is the destination (unix cp).

        Copying a directory requires ``recursive=True`` (cp -r), which
        overlays into existing destination directories like unix does.
        """
        sources, dst = self._split_destination('cp', source, paths)
        src_stats = gather(*(self._backend.stat(src) for src in sources))
        for src, raw in zip(sources, src_stats, strict=True):
            if raw.kind is PathKind.DIRECTORY and not recursive:
                raise IsADirectoryError(src)
        targets = self._plan_destinations(sources, dst)
        gather(
            *(
                generic.copy_tree(self._backend, src, target)
                if raw.kind is PathKind.DIRECTORY
                else self._backend.copy(src, target)
                for src, raw, target in zip(sources, src_stats, targets, strict=True)
            )
        )

    def _split_destination(
        self, op: str, first: StrPathLike, rest: tuple[StrPathLike, ...]
    ) -> tuple[list[StorixPath], StorixPath]:
        """Split unix-style variadic arguments into (sources, destination)."""
        if not rest:
            msg = f'{op}() needs a source and a destination: {op}(src, ..., dst)'
            raise TypeError(msg)
        *more, dst = rest
        sources = [self._resolve(p) for p in (first, *more)]
        return sources, self._resolve(dst)

    def _plan_destinations(
        self, sources: list[StorixPath], dst: StorixPath
    ) -> list[StorixPath]:
        """Map sources onto final target paths, honoring unix semantics.

        An existing directory destination receives the sources *inside*
        it; anything else is a rename target, valid only for a single
        source and requiring an existing parent.
        """
        try:
            dst_kind = (self._backend.stat(dst)).kind
        except PathNotFoundError:
            dst_kind = None

        if dst_kind is PathKind.DIRECTORY:
            return [dst / src.name for src in sources]
        if len(sources) > 1:
            raise NotADirectoryError(dst)
        self._ensure_parent(dst)
        return [dst]
