# DO NOT EDIT - GENERATED by scripts/unasync.py
# source of truth: src/storix/_async/layers.py
"""Port middleware: backends that wrap backends.

A layer implements the same ``StorageBackend`` protocol it consumes, so
layers compose with backends and with each other. Cross-cutting concerns
(sandboxing now; caching, metadata, observability later) live here
rather than inside the core or any backend.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from storix import pathops
from storix.errors import PathError, PermissionDeniedError
from storix.types import StorixPath


if TYPE_CHECKING:
    from collections.abc import Iterator, Mapping
    from pathlib import PurePosixPath

    from storix.models import Capabilities, Entry, RawStat
    from storix.types import EchoMode, StrPathLike

    from .backends import StorageBackend


_ROOT = StorixPath('/')


class SandboxLayer:
    """Confine any backend beneath a virtual root - chroot as middleware.

    Every incoming port path is re-anchored under ``root`` after lexical
    normalization, so traversal cannot escape even when a caller bypasses
    the core's resolution. Errors surfacing from the inner backend are
    re-scoped back into the virtual namespace, so the real prefix never
    leaks through error paths or tracebacks.
    """

    capabilities: Capabilities

    def __init__(self, backend: StorageBackend, *, root: StrPathLike) -> None:
        self._inner = backend
        self._root = pathops.resolve(root, cwd=_ROOT, home=_ROOT)
        self.capabilities = backend.capabilities

    # --- scoping machinery ---

    def to_real(self, path: StrPathLike) -> StorixPath:
        """Translate a virtual (sandboxed) path to its real inner path.

        The privileged escape hatch for code that *owns* the layer -
        e.g. writing real paths to an audit store while the sandboxed
        session only ever sees virtual ones.
        """
        virtual = pathops.normalize(path)  # clamps '..' inside virtual space
        real = StorixPath(self._root, *virtual.parts[1:])
        if not real.is_relative_to(self._root):  # defense in depth
            raise PermissionDeniedError(path)
        return real

    def to_virtual(self, real: StrPathLike) -> StorixPath:
        """Translate a real inner path back into the virtual namespace.

        Paths outside the sandbox root pass through unchanged.
        """
        p = StorixPath(real)
        if p.is_relative_to(self._root):
            return StorixPath('/', *p.relative_to(self._root).parts)
        return p

    def _rescope(self, exc: PathError) -> PathError:
        """Rebuild an inner error in the caller's virtual namespace."""
        return type(exc)(self.to_virtual(exc.path))

    # --- the port, delegated under translation ---

    def read(self, path: PurePosixPath) -> bytes:
        """Return the full contents of a file."""
        try:
            return self._inner.read(self.to_real(path))
        except PathError as exc:
            raise self._rescope(exc) from None

    def read_stream(self, path: PurePosixPath) -> Iterator[bytes]:
        """Stream a file's contents in chunks."""
        try:
            yield from self._inner.read_stream(self.to_real(path))
        except PathError as exc:
            raise self._rescope(exc) from None

    def write(
        self,
        path: PurePosixPath,
        data: Iterator[bytes],
        *,
        mode: EchoMode,
        content_type: str | None,
        metadata: Mapping[str, str] | None = None,
    ) -> None:
        """Write a file from a chunk stream."""
        try:
            self._inner.write(
                self.to_real(path),
                data,
                mode=mode,
                content_type=content_type,
                metadata=metadata,
            )
        except PathError as exc:
            raise self._rescope(exc) from None

    def delete(self, path: PurePosixPath) -> None:
        """Delete a leaf: a file or an empty directory."""
        try:
            self._inner.delete(self.to_real(path))
        except PathError as exc:
            raise self._rescope(exc) from None

    def list_dir(self, path: PurePosixPath) -> Iterator[Entry]:
        """Yield the direct children of a directory (names need no scoping)."""
        try:
            yield from self._inner.list_dir(self.to_real(path))
        except PathError as exc:
            raise self._rescope(exc) from None

    def stat(self, path: PurePosixPath) -> RawStat:
        """Return raw facts about a path."""
        try:
            return self._inner.stat(self.to_real(path))
        except PathError as exc:
            raise self._rescope(exc) from None

    def make_dir(self, path: PurePosixPath, *, parents: bool) -> None:
        """Create a directory."""
        try:
            self._inner.make_dir(self.to_real(path), parents=parents)
        except PathError as exc:
            raise self._rescope(exc) from None

    def exists(self, path: PurePosixPath) -> bool:
        """Whether anything lives at ``path``."""
        try:
            return self._inner.exists(self.to_real(path))
        except PathError as exc:
            raise self._rescope(exc) from None

    def move(self, src: PurePosixPath, dst: PurePosixPath) -> None:
        """Move a file or directory tree."""
        try:
            self._inner.move(self.to_real(src), self.to_real(dst))
        except PathError as exc:
            raise self._rescope(exc) from None

    def copy(self, src: PurePosixPath, dst: PurePosixPath) -> None:
        """Copy a single file."""
        try:
            self._inner.copy(self.to_real(src), self.to_real(dst))
        except PathError as exc:
            raise self._rescope(exc) from None

    def delete_tree(self, path: PurePosixPath) -> None:
        """Delete ``path`` and everything below it."""
        try:
            self._inner.delete_tree(self.to_real(path))
        except PathError as exc:
            raise self._rescope(exc) from None

    def du(self, path: PurePosixPath) -> int:
        """Total size in bytes of the tree rooted at ``path``."""
        try:
            return self._inner.du(self.to_real(path))
        except PathError as exc:
            raise self._rescope(exc) from None

    def set_metadata(self, path: PurePosixPath, metadata: Mapping[str, str]) -> None:
        """Replace a file's custom metadata."""
        try:
            self._inner.set_metadata(self.to_real(path), metadata)
        except PathError as exc:
            raise self._rescope(exc) from None

    def make_url(self, path: PurePosixPath, *, expires_in: int | None = None) -> str:
        """Mint a shareable URL for a file."""
        try:
            return self._inner.make_url(self.to_real(path), expires_in=expires_in)
        except PathError as exc:
            raise self._rescope(exc) from None

    def close(self) -> None:
        """Release the inner backend's resources."""
        self._inner.close()


class PassthroughLayer:
    """Base class for custom layers: full delegation, override what matters.

    Unlike ``__getattr__``-based delegation, every port method is written
    out, so subclasses satisfy the ``StorageBackend`` protocol
    *statically* - type checkers accept them anywhere a backend goes.
    Override the operations your layer changes, and reassign
    ``capabilities`` (e.g. via ``dataclasses.replace``) when it adds one.
    """

    capabilities: Capabilities

    def __init__(self, backend: StorageBackend) -> None:
        self._inner = backend
        self.capabilities = backend.capabilities

    def read(self, path: PurePosixPath) -> bytes:
        """Return the full contents of a file."""
        return self._inner.read(path)

    def read_stream(self, path: PurePosixPath) -> Iterator[bytes]:
        """Stream a file's contents in chunks."""
        yield from self._inner.read_stream(path)

    def write(
        self,
        path: PurePosixPath,
        data: Iterator[bytes],
        *,
        mode: EchoMode,
        content_type: str | None,
        metadata: Mapping[str, str] | None = None,
    ) -> None:
        """Write a file from a chunk stream."""
        self._inner.write(
            path, data, mode=mode, content_type=content_type, metadata=metadata
        )

    def delete(self, path: PurePosixPath) -> None:
        """Delete a leaf: a file or an empty directory."""
        self._inner.delete(path)

    def list_dir(self, path: PurePosixPath) -> Iterator[Entry]:
        """Yield the direct children of a directory."""
        yield from self._inner.list_dir(path)

    def stat(self, path: PurePosixPath) -> RawStat:
        """Return raw facts about a path."""
        return self._inner.stat(path)

    def make_dir(self, path: PurePosixPath, *, parents: bool) -> None:
        """Create a directory."""
        self._inner.make_dir(path, parents=parents)

    def exists(self, path: PurePosixPath) -> bool:
        """Whether anything lives at ``path``."""
        return self._inner.exists(path)

    def move(self, src: PurePosixPath, dst: PurePosixPath) -> None:
        """Move a file or directory tree."""
        self._inner.move(src, dst)

    def copy(self, src: PurePosixPath, dst: PurePosixPath) -> None:
        """Copy a single file."""
        self._inner.copy(src, dst)

    def delete_tree(self, path: PurePosixPath) -> None:
        """Delete ``path`` and everything below it."""
        self._inner.delete_tree(path)

    def du(self, path: PurePosixPath) -> int:
        """Total content size in bytes of the tree rooted at ``path``."""
        return self._inner.du(path)

    def set_metadata(self, path: PurePosixPath, metadata: Mapping[str, str]) -> None:
        """Replace a file's custom metadata."""
        self._inner.set_metadata(path, metadata)

    def make_url(self, path: PurePosixPath, *, expires_in: int | None = None) -> str:
        """Mint a shareable URL for a file."""
        return self._inner.make_url(path, expires_in=expires_in)

    def close(self) -> None:
        """Release the inner backend's resources."""
        self._inner.close()
