# DO NOT EDIT - GENERATED by scripts/unasync.py
# source of truth: src/storix/_async/layers.py
"""Port middleware: backends that wrap backends.

A layer implements the same ``StorageBackend`` protocol it consumes, so
layers compose with backends and with each other. Cross-cutting concerns
(sandboxing now; caching, metadata, observability later) live here
rather than inside the core or any backend.
"""
# ruff: noqa: A004 - storix error classes intentionally shadow stdlib names

from __future__ import annotations

import dataclasses
import time

from typing import TYPE_CHECKING

from storix import pathops
from storix._sync._stream import ensure_chunks
from storix.enums import Capability, PathKind
from storix.errors import (
    IsADirectoryError,
    PathError,
    PathNotFoundError,
    PermissionDeniedError,
)
from storix.serialization import json_dumpb, json_loadb
from storix.types import StorixPath


if TYPE_CHECKING:
    from collections.abc import Callable, Iterator, Mapping
    from pathlib import PurePosixPath
    from typing import Any, ClassVar

    from storix.models import Capabilities, Entry, RawStat
    from storix.types import EchoMode, StrPathLike

    from .backends import StorageBackend

    BoundLayer = Callable[[StorageBackend], StorageBackend]


_ROOT = StorixPath('/')


class SandboxLayer:
    """Confine any backend beneath a virtual root - chroot as middleware.

    Every incoming port path is re-anchored under ``root`` after lexical
    normalization, so traversal cannot escape even when a caller bypasses
    the core's resolution. Errors surfacing from the inner backend are
    re-scoped back into the virtual namespace, so the real prefix never
    leaks through error paths or tracebacks.
    """

    capabilities: Capabilities

    def __init__(self, backend: StorageBackend, *, root: StrPathLike) -> None:
        self._inner = backend
        self._root = pathops.resolve(root, cwd=_ROOT, home=_ROOT)
        self.capabilities = backend.capabilities

    # --- scoping machinery ---

    def to_real(self, path: StrPathLike) -> StorixPath:
        """Translate a virtual (sandboxed) path to its real inner path.

        The privileged escape hatch for code that *owns* the layer -
        e.g. writing real paths to an audit store while the sandboxed
        session only ever sees virtual ones.
        """
        virtual = pathops.normalize(path)  # clamps '..' inside virtual space
        real = StorixPath(self._root, *virtual.parts[1:])
        if not real.is_relative_to(self._root):  # defense in depth
            raise PermissionDeniedError(path)
        return real

    def to_virtual(self, real: StrPathLike) -> StorixPath:
        """Translate a real inner path back into the virtual namespace.

        Paths outside the sandbox root pass through unchanged.
        """
        p = StorixPath(real)
        if p.is_relative_to(self._root):
            return StorixPath('/', *p.relative_to(self._root).parts)
        return p

    def _rescope(self, exc: PathError) -> PathError:
        """Rebuild an inner error in the caller's virtual namespace."""
        return type(exc)(self.to_virtual(exc.path))

    # --- the port, delegated under translation ---

    def read(self, path: PurePosixPath) -> bytes:
        """Return the full contents of a file."""
        try:
            return self._inner.read(self.to_real(path))
        except PathError as exc:
            raise self._rescope(exc) from None

    def read_stream(self, path: PurePosixPath) -> Iterator[bytes]:
        """Stream a file's contents in chunks."""
        try:
            yield from self._inner.read_stream(self.to_real(path))
        except PathError as exc:
            raise self._rescope(exc) from None

    def write(
        self,
        path: PurePosixPath,
        data: Iterator[bytes],
        *,
        mode: EchoMode,
        content_type: str | None,
        metadata: Mapping[str, str] | None = None,
    ) -> None:
        """Write a file from a chunk stream."""
        try:
            self._inner.write(
                self.to_real(path),
                data,
                mode=mode,
                content_type=content_type,
                metadata=metadata,
            )
        except PathError as exc:
            raise self._rescope(exc) from None

    def delete(self, path: PurePosixPath) -> None:
        """Delete a leaf: a file or an empty directory."""
        try:
            self._inner.delete(self.to_real(path))
        except PathError as exc:
            raise self._rescope(exc) from None

    def list_dir(self, path: PurePosixPath) -> Iterator[Entry]:
        """Yield the direct children of a directory (names need no scoping)."""
        try:
            yield from self._inner.list_dir(self.to_real(path))
        except PathError as exc:
            raise self._rescope(exc) from None

    def stat(self, path: PurePosixPath) -> RawStat:
        """Return raw facts about a path."""
        try:
            return self._inner.stat(self.to_real(path))
        except PathError as exc:
            raise self._rescope(exc) from None

    def make_dir(self, path: PurePosixPath, *, parents: bool) -> None:
        """Create a directory."""
        try:
            self._inner.make_dir(self.to_real(path), parents=parents)
        except PathError as exc:
            raise self._rescope(exc) from None

    def exists(self, path: PurePosixPath) -> bool:
        """Whether anything lives at ``path``."""
        try:
            return self._inner.exists(self.to_real(path))
        except PathError as exc:
            raise self._rescope(exc) from None

    def move(self, src: PurePosixPath, dst: PurePosixPath) -> None:
        """Move a file or directory tree."""
        try:
            self._inner.move(self.to_real(src), self.to_real(dst))
        except PathError as exc:
            raise self._rescope(exc) from None

    def copy(self, src: PurePosixPath, dst: PurePosixPath) -> None:
        """Copy a single file."""
        try:
            self._inner.copy(self.to_real(src), self.to_real(dst))
        except PathError as exc:
            raise self._rescope(exc) from None

    def delete_tree(self, path: PurePosixPath) -> None:
        """Delete ``path`` and everything below it."""
        try:
            self._inner.delete_tree(self.to_real(path))
        except PathError as exc:
            raise self._rescope(exc) from None

    def du(self, path: PurePosixPath) -> int:
        """Total size in bytes of the tree rooted at ``path``."""
        try:
            return self._inner.du(self.to_real(path))
        except PathError as exc:
            raise self._rescope(exc) from None

    def set_metadata(self, path: PurePosixPath, metadata: Mapping[str, str]) -> None:
        """Replace a file's custom metadata."""
        try:
            self._inner.set_metadata(self.to_real(path), metadata)
        except PathError as exc:
            raise self._rescope(exc) from None

    def make_url(self, path: PurePosixPath, *, expires_in: int | None = None) -> str:
        """Mint a shareable URL for a file."""
        try:
            return self._inner.make_url(self.to_real(path), expires_in=expires_in)
        except PathError as exc:
            raise self._rescope(exc) from None

    def locate(self, path: PurePosixPath) -> str:
        """Locator of the *real* underlying path - the audit primitive.

        A sandboxed session's ``fs.locate('/x')`` returns the physical
        location (``file:///srv/data/tenant-42/x``), no privileged
        ``to_real`` dance required.
        """
        return self._inner.locate(self.to_real(path))

    def close(self) -> None:
        """Release the inner backend's resources."""
        self._inner.close()


class LayerBase:
    """Base class for custom layers: full delegation, override what matters.

    Unlike ``__getattr__``-based delegation, every port method is written
    out, so subclasses satisfy the ``StorageBackend`` protocol
    *statically* - type checkers accept them anywhere a backend goes.
    Override the operations your layer changes, and reassign
    ``capabilities`` (e.g. via ``dataclasses.replace``) when it adds one.

    Used unsubclassed it is a harmless pure passthrough - occasionally
    useful for measuring layer overhead, never required.

    Set ``provides`` on a layer that backfills a capability; then
    ``fs.with_layer_missing(TheLayer)`` needs no capability argument - it
    is inferred (see ``DataUrlLayer``/``MetadataLayer``).
    """

    provides: ClassVar[Capability | None] = None
    """The capability this layer backfills, if any (used by native-preference)."""

    capabilities: Capabilities

    def __init__(self, backend: StorageBackend) -> None:
        self._inner = backend
        self.capabilities = backend.capabilities

    def read(self, path: PurePosixPath) -> bytes:
        """Return the full contents of a file."""
        return self._inner.read(path)

    def read_stream(self, path: PurePosixPath) -> Iterator[bytes]:
        """Stream a file's contents in chunks."""
        yield from self._inner.read_stream(path)

    def write(
        self,
        path: PurePosixPath,
        data: Iterator[bytes],
        *,
        mode: EchoMode,
        content_type: str | None,
        metadata: Mapping[str, str] | None = None,
    ) -> None:
        """Write a file from a chunk stream."""
        self._inner.write(
            path, data, mode=mode, content_type=content_type, metadata=metadata
        )

    def delete(self, path: PurePosixPath) -> None:
        """Delete a leaf: a file or an empty directory."""
        self._inner.delete(path)

    def list_dir(self, path: PurePosixPath) -> Iterator[Entry]:
        """Yield the direct children of a directory."""
        yield from self._inner.list_dir(path)

    def stat(self, path: PurePosixPath) -> RawStat:
        """Return raw facts about a path."""
        return self._inner.stat(path)

    def make_dir(self, path: PurePosixPath, *, parents: bool) -> None:
        """Create a directory."""
        self._inner.make_dir(path, parents=parents)

    def exists(self, path: PurePosixPath) -> bool:
        """Whether anything lives at ``path``."""
        return self._inner.exists(path)

    def move(self, src: PurePosixPath, dst: PurePosixPath) -> None:
        """Move a file or directory tree."""
        self._inner.move(src, dst)

    def copy(self, src: PurePosixPath, dst: PurePosixPath) -> None:
        """Copy a single file."""
        self._inner.copy(src, dst)

    def delete_tree(self, path: PurePosixPath) -> None:
        """Delete ``path`` and everything below it."""
        self._inner.delete_tree(path)

    def du(self, path: PurePosixPath) -> int:
        """Total content size in bytes of the tree rooted at ``path``."""
        return self._inner.du(path)

    def set_metadata(self, path: PurePosixPath, metadata: Mapping[str, str]) -> None:
        """Replace a file's custom metadata."""
        self._inner.set_metadata(path, metadata)

    def make_url(self, path: PurePosixPath, *, expires_in: int | None = None) -> str:
        """Mint a shareable URL for a file."""
        return self._inner.make_url(path, expires_in=expires_in)

    def locate(self, path: PurePosixPath) -> str:
        """Fully-qualified physical locator for a port path."""
        return self._inner.locate(path)

    def close(self) -> None:
        """Release the inner backend's resources."""
        self._inner.close()


def when_missing(capability: Capability, layer: BoundLayer) -> BoundLayer:
    """Apply ``layer`` only when the backend lacks ``capability``.

    The native-preference combinator: the same construction code works
    across providers, wrapping capability-poor backends and
    short-circuiting entirely (zero overhead, native behavior) on
    backends that already advertise the capability::

        Storix(backend, layers=[when_missing(Capability.PRESIGNED_URLS, DataUrlLayer)])

    Prefer-the-layer is expressed by not using the combinator.
    """

    def build(backend: StorageBackend) -> StorageBackend:
        if backend.capabilities.supports(capability):
            return backend
        return layer(backend)

    return build


class DataUrlLayer(LayerBase):
    """``url()`` everywhere, via ``data:`` URLs.

    Upgrades ``presigned_urls`` by inlining the entire file as base64
    into the URL itself. Fine for small assets and HTML embedding;
    *terrible* for LLM/agent contexts (a 1 MiB file becomes a ~1.4 M
    character URL) and for anything large. Prefer native presigned URLs
    when the backend has them::

        fs.with_layer_missing(DataUrlLayer)  # capability inferred

    ``expires_in`` is ignored - data URLs cannot expire (the advisory
    contract permits this).
    """

    provides = Capability.PRESIGNED_URLS

    def __init__(self, backend: StorageBackend) -> None:
        super().__init__(backend)
        self.capabilities = dataclasses.replace(
            backend.capabilities, presigned_urls=True
        )

    def make_url(self, path: PurePosixPath, *, expires_in: int | None = None) -> str:
        """Inline the file as a base64 ``data:`` URL."""
        del expires_in  # data URLs cannot expire
        from storix.utils import to_data_url

        return to_data_url(buf=self._inner.read(path))


class MetadataLayer(LayerBase):
    """Custom metadata for backends without native support, via a sidecar.

    Upgrades ``custom_metadata`` by keeping a hidden JSON table
    (``/.storix-meta.json``) *inside the wrapped backend itself*, so it
    works over any backend and travels with the data. Port semantics are
    preserved exactly (replace; ``{}`` clears; ``None`` preserves on
    append) - the conformance suite runs against this layer.

    Honest limits: the sidecar is last-writer-wins under concurrent
    writers; every stat/metadata operation costs one extra sidecar read;
    external writes that bypass the layer leave stale entries (a delete
    through the layer cleans up). ``copy`` does not carry metadata, per
    the port contract. Prefer native metadata when available::

        fs.with_layer_missing(MetadataLayer)  # capability inferred

    ``serialize``/``deserialize`` swap the sidecar codec (default: stdlib
    json). They are object<->*bytes* callables (not str), so pass
    ``orjson.dumps``/``orjson.loads`` or a custom ``.dumpb``/``.loads`` -
    NOT ``json.dumps`` (which returns str).
    """

    provides = Capability.CUSTOM_METADATA
    _SIDECAR = StorixPath('/.storix-meta.json')

    def __init__(
        self,
        backend: StorageBackend,
        *,
        serialize: Callable[[Any], bytes] = json_dumpb,
        deserialize: Callable[[bytes], Any] = json_loadb,
    ) -> None:
        super().__init__(backend)
        self.capabilities = dataclasses.replace(
            backend.capabilities, custom_metadata=True
        )
        self._serialize = serialize
        self._deserialize = deserialize

    def _load(self) -> dict[str, dict[str, str]]:
        try:
            raw = self._inner.read(self._SIDECAR)
        except PathNotFoundError:
            return {}
        return self._deserialize(raw) if raw else {}

    def _save(self, table: dict[str, dict[str, str]]) -> None:
        if table:
            payload = self._serialize(table)
            self._inner.write(
                self._SIDECAR, ensure_chunks(payload), mode='w', content_type=None
            )
        elif self._inner.exists(self._SIDECAR):
            self._inner.delete(self._SIDECAR)

    def write(
        self,
        path: PurePosixPath,
        data: Iterator[bytes],
        *,
        mode: EchoMode,
        content_type: str | None,
        metadata: Mapping[str, str] | None = None,
    ) -> None:
        """Write content, then maintain the sidecar per port semantics."""
        self._inner.write(path, data, mode=mode, content_type=content_type)
        key = str(path)
        if metadata is None and mode == 'a':
            return  # None preserves on append
        table = self._load()
        if metadata:
            table[key] = dict(metadata)
        else:  # create/truncate without metadata, or explicit {} clear
            table.pop(key, None)
        self._save(table)

    def stat(self, path: PurePosixPath) -> RawStat:
        """Merge sidecar metadata into the inner stat."""
        if path == self._SIDECAR:  # the sidecar is invisible to consumers
            raise PathNotFoundError(path)
        raw = self._inner.stat(path)
        if raw.kind is not PathKind.FILE:
            return raw
        table = self._load()
        stored = table.get(str(path))
        return dataclasses.replace(raw, metadata=dict(stored) if stored else None)

    def exists(self, path: PurePosixPath) -> bool:
        """Whether anything lives at ``path`` (the sidecar reads absent)."""
        if path == self._SIDECAR:
            return False
        return self._inner.exists(path)

    def read_stream(self, path: PurePosixPath) -> Iterator[bytes]:
        """Stream a file's contents (the sidecar is not readable)."""
        if path == self._SIDECAR:
            raise PathNotFoundError(path)
        yield from self._inner.read_stream(path)

    def list_dir(self, path: PurePosixPath) -> Iterator[Entry]:
        """Yield children, hiding the sidecar from its parent directory."""
        for entry in self._inner.list_dir(path):
            if path / entry.name != self._SIDECAR:
                yield entry

    def du(self, path: PurePosixPath) -> int:
        """Tree size excluding the sidecar (walks via this layer)."""
        from .backends import generic

        return generic.du(self, path)

    def set_metadata(self, path: PurePosixPath, metadata: Mapping[str, str]) -> None:
        """Replace a file's metadata in the sidecar."""
        raw = self._inner.stat(path)  # raises for missing paths
        if raw.kind is not PathKind.FILE:
            raise IsADirectoryError(path)
        table = self._load()
        if metadata:
            table[str(path)] = dict(metadata)
        else:
            table.pop(str(path), None)
        self._save(table)

    def delete(self, path: PurePosixPath) -> None:
        """Delete the leaf and drop its sidecar entry."""
        self._inner.delete(path)
        table = self._load()
        if table.pop(str(path), None) is not None:
            self._save(table)

    def delete_tree(self, path: PurePosixPath) -> None:
        """Delete the tree and every sidecar entry beneath it."""
        self._inner.delete_tree(path)
        prefix = str(path).rstrip('/') + '/'
        table = self._load()
        kept = {
            key: value
            for key, value in table.items()
            if key != str(path) and not key.startswith(prefix)
        }
        if kept != table:
            self._save(kept)

    def move(self, src: PurePosixPath, dst: PurePosixPath) -> None:
        """Move content and re-key sidecar entries (trees included)."""
        self._inner.move(src, dst)
        src_key, dst_key = str(src), str(dst)
        src_prefix = src_key.rstrip('/') + '/'
        table = self._load()
        moved: dict[str, dict[str, str]] = {}
        for key in list(table):
            if key == src_key:
                moved[dst_key] = table.pop(key)
            elif key.startswith(src_prefix):
                moved[dst_key + key.removeprefix(src_key)] = table.pop(key)
        if moved:
            table.update(moved)
            self._save(table)


# distinct from a cached ``None`` (a known-absent path)
_MISS: object = object()


class CacheLayer(LayerBase):
    """Read-through cache for metadata: stat / list_dir / exists.

    Serves the operations navigation hammers (``ls``, ``cd``, ``tree``)
    from memory after the first hit - a big win on network backends where
    each is a round-trip. ``read`` stays a pass-through (content is not
    cached in this version).

    Every mutation *through this layer* evicts the entries it affects, so
    the session always sees its own writes. Not a capability (``provides``
    stays None): compose with ``with_layer(CacheLayer, ttl=...)``.

    .. warning::
       Correctness assumes yours is the only writer of this store. The
       cache cannot see changes made *outside* this layer (another
       process, a second storix session, the cloud console). If the store
       has other writers, pass ``ttl`` (seconds) to bound how long a stale
       entry can live - the default ``None`` never expires and is only
       safe for a single owner.
    """

    def __init__(self, backend: StorageBackend, *, ttl: float | None = None) -> None:
        super().__init__(backend)
        self._ttl = ttl
        self._stat: dict[str, tuple[float, RawStat | None]] = {}
        self._list: dict[str, tuple[float, list[Entry]]] = {}

    # --- cache primitives ---

    def _get(self, cache: dict, key: str) -> object:
        entry = cache.get(key)
        if entry is None:
            return _MISS
        stamped, value = entry
        if self._ttl is not None and time.monotonic() - stamped > self._ttl:
            cache.pop(key, None)
            return _MISS
        return value

    def _put(self, cache: dict, key: str, value: object) -> None:
        cache[key] = (time.monotonic(), value)

    def _evict(self, path: PurePosixPath) -> None:
        self._stat.pop(str(path), None)
        self._list.pop(str(path), None)  # the path's own listing (if a dir)
        self._list.pop(str(path.parent), None)  # parent listing membership changed

    def _evict_tree(self, path: PurePosixPath) -> None:
        prefix = str(path).rstrip('/') + '/'
        for cache in (self._stat, self._list):
            for key in [k for k in cache if k == str(path) or k.startswith(prefix)]:
                cache.pop(key, None)
        self._list.pop(str(path.parent), None)

    # --- cached reads ---

    def stat(self, path: PurePosixPath) -> RawStat:
        """Return raw facts, cached (negatives cached as absent too)."""
        cached = self._get(self._stat, str(path))
        if cached is not _MISS:
            if cached is None:
                raise PathNotFoundError(path)
            return cached  # type: ignore[return-value]
        try:
            raw = self._inner.stat(path)
        except PathNotFoundError:
            self._put(self._stat, str(path), None)
            raise
        self._put(self._stat, str(path), raw)
        return raw

    def exists(self, path: PurePosixPath) -> bool:
        """Derive existence from the stat cache (shares one cache)."""
        try:
            self.stat(path)
        except PathNotFoundError:
            return False
        return True

    def list_dir(self, path: PurePosixPath) -> Iterator[Entry]:
        """Yield children, cached as a materialized list."""
        cached = self._get(self._list, str(path))
        if cached is not _MISS:
            for entry in cached:  # type: ignore[union-attr]
                yield entry
            return
        entries = list(self._inner.list_dir(path))
        self._put(self._list, str(path), entries)
        for entry in entries:
            yield entry

    # --- mutations evict, then delegate ---

    def write(
        self,
        path: PurePosixPath,
        data: Iterator[bytes],
        *,
        mode: EchoMode,
        content_type: str | None,
        metadata: Mapping[str, str] | None = None,
    ) -> None:
        """Write, then evict the path and its parent listing."""
        self._inner.write(
            path, data, mode=mode, content_type=content_type, metadata=metadata
        )
        self._evict(path)

    def delete(self, path: PurePosixPath) -> None:
        """Delete a leaf, then evict it and its parent listing."""
        self._inner.delete(path)
        self._evict(path)

    def delete_tree(self, path: PurePosixPath) -> None:
        """Delete a tree, then evict every cached entry beneath it."""
        self._inner.delete_tree(path)
        self._evict_tree(path)

    def make_dir(self, path: PurePosixPath, *, parents: bool) -> None:
        """Create a directory, then evict it and its parent listing."""
        self._inner.make_dir(path, parents=parents)
        self._evict(path)

    def move(self, src: PurePosixPath, dst: PurePosixPath) -> None:
        """Move, then evict both subtrees."""
        self._inner.move(src, dst)
        self._evict_tree(src)
        self._evict_tree(dst)

    def copy(self, src: PurePosixPath, dst: PurePosixPath) -> None:
        """Copy, then evict the destination."""
        self._inner.copy(src, dst)
        self._evict(dst)

    def set_metadata(self, path: PurePosixPath, metadata: Mapping[str, str]) -> None:
        """Replace metadata, then evict the path's cached stat."""
        self._inner.set_metadata(path, metadata)
        self._evict(path)
