# DO NOT EDIT - GENERATED by scripts/unasync.py
# source of truth: src/storix/_async/temporary.py
"""Disposable filesystems for tests and scratch work."""

from __future__ import annotations

import shutil
import tempfile
import uuid

from contextlib import contextmanager
from typing import TYPE_CHECKING

from storix.types import StorixPath

from .backends.local import LocalBackend
from .core import Storix
from .layers import SandboxLayer


if TYPE_CHECKING:
    from collections.abc import Generator

    from .backends import StorageBackend


@contextmanager
def temporary() -> Generator[Storix]:
    """Yield a Storix session over a fresh temporary directory.

    The directory and everything in it are deleted on exit.
    """
    base = tempfile.mkdtemp(prefix='storix-')
    fs = Storix(LocalBackend(base))
    try:
        yield fs
    finally:
        fs.close()
        shutil.rmtree(base, ignore_errors=True)


@contextmanager
def scratch(backend: StorageBackend, *, prefix: str = 'scratch-') -> Generator[Storix]:
    """Yield an ephemeral workspace on *any* backend.

    Pure composition: a uniquely-named subtree, sandboxed so the session
    sees it as ``/``, deleted on exit. The backend is borrowed, not
    owned - its lifecycle (``close``) stays with the caller.
    """
    root = StorixPath(f'/{prefix}{uuid.uuid4().hex[:12]}')
    backend.make_dir(root, parents=True)
    try:
        yield Storix(SandboxLayer(backend, root=root))
    finally:
        backend.delete_tree(root)
