# DO NOT EDIT - GENERATED by scripts/unasync.py
# source of truth: src/storix/_async/temporary.py
"""Disposable local filesystems for tests and scratch work."""

from __future__ import annotations

import shutil
import tempfile

from contextlib import contextmanager
from typing import TYPE_CHECKING

from .backends.local import LocalBackend
from .core import Storix


if TYPE_CHECKING:
    from collections.abc import Generator


@contextmanager
def temporary() -> Generator[Storix]:
    """Yield a Storix session over a fresh temporary directory.

    The directory and everything in it are deleted on exit.
    """
    base = tempfile.mkdtemp(prefix='storix-')
    fs = Storix(LocalBackend(base))
    try:
        yield fs
    finally:
        fs.close()
        shutil.rmtree(base, ignore_errors=True)
