# DO NOT EDIT - GENERATED by scripts/unasync.py
# source of truth: src/storix/_async/layers/base.py
"""LayerBase: the delegating base for custom layers."""

from __future__ import annotations

from typing import TYPE_CHECKING

from storix._sync._stream import validate_chunk_size


if TYPE_CHECKING:
    from collections.abc import Iterator, Mapping
    from pathlib import PurePosixPath
    from typing import ClassVar

    from storix.enums import Capability
    from storix.models import Capabilities, Entry, RawStat
    from storix.types import EchoMode

    from ..backends import StorageBackend


class LayerBase:
    """Base class for custom layers: full delegation, override what matters.

    Unlike ``__getattr__``-based delegation, every port method is written
    out, so subclasses satisfy the ``StorageBackend`` protocol
    *statically* - type checkers accept them anywhere a backend goes.
    Override the operations your layer changes, and reassign
    ``capabilities`` (e.g. via ``dataclasses.replace``) when it adds one.

    Used unsubclassed it is a harmless pure passthrough - occasionally
    useful for measuring layer overhead, never required.

    Set ``provides`` on a layer that backfills a capability; then
    ``fs.with_layer_missing(TheLayer)`` needs no capability argument - it
    is inferred (see ``DataUrlLayer``/``MetadataLayer``).
    """

    provides: ClassVar[Capability | None] = None
    """The capability this layer backfills, if any (used by native-preference)."""

    removable: ClassVar[bool] = True
    """Whether ``Storix.without_layer`` may strip this layer. A layer that is
    a guarantee (e.g. a sandbox) sets this ``False`` so it can never be
    bypassed."""

    capabilities: Capabilities

    def __init__(self, backend: StorageBackend) -> None:
        self._inner = backend
        self.capabilities = backend.capabilities

    def read(self, path: PurePosixPath) -> bytes:
        """Return the full contents of a file."""
        return self._inner.read(path)

    def read_stream(
        self, path: PurePosixPath, *, chunk_size: int | None = None
    ) -> Iterator[bytes]:
        """Stream a file's contents in bounded chunks.

        Raises:
            ValueError: If ``chunk_size`` is zero or negative.
        """
        validate_chunk_size(chunk_size)
        yield from self._inner.read_stream(path, chunk_size=chunk_size)

    def write(
        self,
        path: PurePosixPath,
        data: bytes,
        *,
        mode: EchoMode,
        content_type: str | None,
        metadata: Mapping[str, str] | None = None,
    ) -> None:
        """Write complete contents through this layer's stream path."""
        from ..backends import generic

        generic.write(
            self,
            path,
            data,
            mode=mode,
            content_type=content_type,
            metadata=metadata,
        )

    def write_stream(
        self,
        path: PurePosixPath,
        data: Iterator[bytes],
        *,
        chunk_size: int | None = None,
        mode: EchoMode,
        content_type: str | None,
        metadata: Mapping[str, str] | None = None,
    ) -> None:
        """Write a file from a bounded chunk stream.

        Raises:
            ValueError: If ``chunk_size`` is zero or negative.
        """
        validate_chunk_size(chunk_size)
        self._inner.write_stream(
            path,
            data,
            chunk_size=chunk_size,
            mode=mode,
            content_type=content_type,
            metadata=metadata,
        )

    def delete(self, path: PurePosixPath) -> None:
        """Delete a leaf: a file or an empty directory."""
        self._inner.delete(path)

    def list_dir(self, path: PurePosixPath) -> Iterator[Entry]:
        """Yield the direct children of a directory."""
        yield from self._inner.list_dir(path)

    def list_tree(self, path: PurePosixPath) -> Iterator[PurePosixPath]:
        """Yield every descendant path under a directory (bulk_listing)."""
        yield from self._inner.list_tree(path)

    def stat(self, path: PurePosixPath) -> RawStat:
        """Return raw facts about a path."""
        return self._inner.stat(path)

    def make_dir(self, path: PurePosixPath, *, parents: bool) -> None:
        """Create a directory."""
        self._inner.make_dir(path, parents=parents)

    def exists(self, path: PurePosixPath) -> bool:
        """Whether anything lives at ``path``."""
        return self._inner.exists(path)

    def move(self, src: PurePosixPath, dst: PurePosixPath) -> None:
        """Move a file or directory tree."""
        self._inner.move(src, dst)

    def copy(self, src: PurePosixPath, dst: PurePosixPath) -> None:
        """Copy a single file."""
        self._inner.copy(src, dst)

    def delete_tree(self, path: PurePosixPath) -> None:
        """Delete ``path`` and everything below it."""
        self._inner.delete_tree(path)

    def du(self, path: PurePosixPath) -> int:
        """Total content size in bytes of the tree rooted at ``path``."""
        return self._inner.du(path)

    def set_metadata(self, path: PurePosixPath, metadata: Mapping[str, str]) -> None:
        """Replace a file's custom metadata."""
        self._inner.set_metadata(path, metadata)

    def make_url(self, path: PurePosixPath, *, expires_in: int | None = None) -> str:
        """Mint a shareable URL for a file."""
        return self._inner.make_url(path, expires_in=expires_in)

    def locate(self, path: PurePosixPath) -> str:
        """Fully-qualified physical locator for a port path."""
        return self._inner.locate(path)

    def close(self) -> None:
        """Release the inner backend's resources."""
        self._inner.close()

    def provision(self) -> bool:
        """Ensure the inner backend's storage root exists (control-plane)."""
        return self._inner.provision()
