# DO NOT EDIT - GENERATED by scripts/unasync.py
# source of truth: src/storix/_async/layers/metadata.py
"""MetadataLayer: custom metadata via a hidden sidecar."""
# ruff: noqa: A004 - storix error classes intentionally shadow stdlib names

from __future__ import annotations

import dataclasses

from typing import TYPE_CHECKING

from storix._sync._stream import ensure_chunks
from storix.enums import Capability, PathKind
from storix.errors import IsADirectoryError, PathNotFoundError
from storix.serialization import json_dumpb, json_loadb
from storix.types import StorixPath

from .base import LayerBase


if TYPE_CHECKING:
    from collections.abc import Callable, Iterator, Mapping
    from pathlib import PurePosixPath
    from typing import Any

    from storix.models import Entry, RawStat
    from storix.types import EchoMode

    from ..backends import StorageBackend


class MetadataLayer(LayerBase):
    """Custom metadata for backends without native support, via a sidecar.

    Upgrades ``custom_metadata`` by keeping a hidden JSON table
    (``/.storix-meta.json``) *inside the wrapped backend itself*, so it
    works over any backend and travels with the data. Port semantics are
    preserved exactly (replace; ``{}`` clears; ``None`` preserves on
    append) - the conformance suite runs against this layer.

    Honest limits: the sidecar is last-writer-wins under concurrent
    writers; every stat/metadata operation costs one extra sidecar read;
    external writes that bypass the layer leave stale entries (a delete
    through the layer cleans up). ``copy`` does not carry metadata, per
    the port contract. Prefer native metadata when available::

        fs.with_layer_missing(MetadataLayer)  # capability inferred

    ``serialize``/``deserialize`` swap the sidecar codec (default: stdlib
    json). They are object<->*bytes* callables (not str), so pass
    ``orjson.dumps``/``orjson.loads`` or a custom ``.dumpb``/``.loads`` -
    NOT ``json.dumps`` (which returns str).
    """

    provides = Capability.CUSTOM_METADATA
    _SIDECAR = StorixPath('/.storix-meta.json')

    def __init__(
        self,
        backend: StorageBackend,
        *,
        serialize: Callable[[Any], bytes] = json_dumpb,
        deserialize: Callable[[bytes], Any] = json_loadb,
    ) -> None:
        super().__init__(backend)
        self.capabilities = dataclasses.replace(
            backend.capabilities, custom_metadata=True
        )
        self._serialize = serialize
        self._deserialize = deserialize

    def _load(self) -> dict[str, dict[str, str]]:
        try:
            raw = self._inner.read(self._SIDECAR)
        except PathNotFoundError:
            return {}
        return self._deserialize(raw) if raw else {}

    def _save(self, table: dict[str, dict[str, str]]) -> None:
        if table:
            payload = self._serialize(table)
            self._inner.write(
                self._SIDECAR, ensure_chunks(payload), mode='w', content_type=None
            )
        elif self._inner.exists(self._SIDECAR):
            self._inner.delete(self._SIDECAR)

    def write(
        self,
        path: PurePosixPath,
        data: Iterator[bytes],
        *,
        mode: EchoMode,
        content_type: str | None,
        metadata: Mapping[str, str] | None = None,
    ) -> None:
        """Write content, then maintain the sidecar per port semantics."""
        self._inner.write(path, data, mode=mode, content_type=content_type)
        key = str(path)
        if metadata is None and mode == 'a':
            return  # None preserves on append
        table = self._load()
        if metadata:
            table[key] = dict(metadata)
        else:  # create/truncate without metadata, or explicit {} clear
            table.pop(key, None)
        self._save(table)

    def stat(self, path: PurePosixPath) -> RawStat:
        """Merge sidecar metadata into the inner stat."""
        if path == self._SIDECAR:  # the sidecar is invisible to consumers
            raise PathNotFoundError(path)
        raw = self._inner.stat(path)
        if raw.kind is not PathKind.FILE:
            return raw
        table = self._load()
        stored = table.get(str(path))
        return dataclasses.replace(raw, metadata=dict(stored) if stored else None)

    def exists(self, path: PurePosixPath) -> bool:
        """Whether anything lives at ``path`` (the sidecar reads absent)."""
        if path == self._SIDECAR:
            return False
        return self._inner.exists(path)

    def read_stream(self, path: PurePosixPath) -> Iterator[bytes]:
        """Stream a file's contents (the sidecar is not readable)."""
        if path == self._SIDECAR:
            raise PathNotFoundError(path)
        yield from self._inner.read_stream(path)

    def list_dir(self, path: PurePosixPath) -> Iterator[Entry]:
        """Yield children, hiding the sidecar from its parent directory."""
        for entry in self._inner.list_dir(path):
            if path / entry.name != self._SIDECAR:
                yield entry

    def du(self, path: PurePosixPath) -> int:
        """Tree size excluding the sidecar (walks via this layer)."""
        from ..backends import generic

        return generic.du(self, path)

    def set_metadata(self, path: PurePosixPath, metadata: Mapping[str, str]) -> None:
        """Replace a file's metadata in the sidecar."""
        raw = self._inner.stat(path)  # raises for missing paths
        if raw.kind is not PathKind.FILE:
            raise IsADirectoryError(path)
        table = self._load()
        if metadata:
            table[str(path)] = dict(metadata)
        else:
            table.pop(str(path), None)
        self._save(table)

    def delete(self, path: PurePosixPath) -> None:
        """Delete the leaf and drop its sidecar entry."""
        self._inner.delete(path)
        table = self._load()
        if table.pop(str(path), None) is not None:
            self._save(table)

    def delete_tree(self, path: PurePosixPath) -> None:
        """Delete the tree and every sidecar entry beneath it."""
        self._inner.delete_tree(path)
        prefix = str(path).rstrip('/') + '/'
        table = self._load()
        kept = {
            key: value
            for key, value in table.items()
            if key != str(path) and not key.startswith(prefix)
        }
        if kept != table:
            self._save(kept)

    def move(self, src: PurePosixPath, dst: PurePosixPath) -> None:
        """Move content and re-key sidecar entries (trees included)."""
        self._inner.move(src, dst)
        src_key, dst_key = str(src), str(dst)
        src_prefix = src_key.rstrip('/') + '/'
        table = self._load()
        moved: dict[str, dict[str, str]] = {}
        for key in list(table):
            if key == src_key:
                moved[dst_key] = table.pop(key)
            elif key.startswith(src_prefix):
                moved[dst_key + key.removeprefix(src_key)] = table.pop(key)
        if moved:
            table.update(moved)
            self._save(table)
