# DO NOT EDIT - GENERATED by scripts/unasync.py
# source of truth: src/storix/_async/layers/observability.py
"""ObservabilityLayer: transfer events counted at the stream boundary."""

from __future__ import annotations

import inspect

from typing import TYPE_CHECKING

from storix._dto import dto
from storix._sync._stream import validate_chunk_size, validate_span

from .base import LayerBase


if TYPE_CHECKING:
    from collections.abc import Callable, Iterator, Mapping
    from pathlib import PurePosixPath
    from typing import Any, Literal

    from storix.types import EchoMode

    from ..backends import StorageBackend


@dto
class TransferEvent:
    """One chunk of transfer progress (see :class:`ObservabilityLayer`)."""

    op: Literal['read', 'write']
    """Which direction the bytes moved."""

    path: PurePosixPath
    """The file being transferred, as this layer sees it."""

    transferred: int
    """Cumulative bytes this stream has moved so far; the consumer owns
    the total."""

    offset: int = 0
    """Where this stream started in the file, and so which stream the
    event belongs to. Zero for a whole-file ``read_stream``/``write_stream``.
    A parallel ``download`` reads one file through several ranges at once,
    each counting its own bytes from zero, so a consumer that accumulates
    per file must key on ``(path, offset)`` rather than on ``path`` alone."""


class ObservabilityLayer(LayerBase):
    """Emit a :class:`TransferEvent` per chunk through the stream port.

    Wraps ``read_stream``/``write_stream`` and counts bytes at the pull
    boundary, so the count tracks backend-acked bytes to within one
    in-flight chunk on any backend (ADR 0019). storix emits only what it
    honestly knows - cumulative bytes; the consumer owns the total (it
    produced the source) and computes any percentage from it.

    The ``sink`` may be sync or async; a coroutine result is awaited per
    event. With no sink the layer is a pure passthrough. Compose it
    outermost so it counts the full logical transfer::

        fs.with_layer(ObservabilityLayer, sink=on_event)
    """

    def __init__(
        self,
        backend: StorageBackend,
        *,
        sink: Callable[[TransferEvent], Any] | None = None,
    ) -> None:
        super().__init__(backend)
        self._sink = sink

    def _count(
        self,
        op: Literal['read', 'write'],
        path: PurePosixPath,
        stream: Iterator[bytes],
        sink: Callable[[TransferEvent], Any],
        offset: int = 0,
    ) -> Iterator[bytes]:
        """Yield ``stream`` unchanged, emitting one event per chunk.

        Args:
            op: Which direction the bytes move.
            path: The file being transferred.
            stream: Chunks to pass through untouched.
            sink: Consumer called once per chunk.
            offset: Where this stream starts in the file, carried on every
                event so a consumer can tell concurrent ranges of one file
                apart.
        """
        transferred = 0
        for chunk in stream:
            transferred += len(chunk)
            result = sink(
                TransferEvent(op=op, path=path, transferred=transferred, offset=offset)
            )
            if inspect.iscoroutine(result):
                # '_ =' keeps the unasync render lint-clean: stripping
                # '' would otherwise leave a bare expression (B018)
                _ = result
            yield chunk

    def read_stream(
        self, path: PurePosixPath, *, chunk_size: int | None = None
    ) -> Iterator[bytes]:
        """Stream a file's contents, emitting an event per chunk.

        Raises:
            ValueError: If ``chunk_size`` is zero or negative.
        """
        validate_chunk_size(chunk_size)
        stream = self._inner.read_stream(path, chunk_size=chunk_size)
        if self._sink is not None:
            stream = self._count('read', path, stream, self._sink)
        yield from stream

    def read_range(
        self,
        path: PurePosixPath,
        *,
        offset: int,
        length: int,
        chunk_size: int | None = None,
    ) -> Iterator[bytes]:
        """Stream one byte range, emitting an event per chunk.

        ``transferred`` counts this range's own bytes, not the file's: a
        parallel download runs several ranges of one file at once, so a
        per-range counter is the only one that stays monotonic per stream.
        The event carries ``offset`` so a sink accumulating a whole
        transfer can tell those streams apart.

        Raises:
            ValueError: If ``offset`` or ``length`` is negative, or if
                ``chunk_size`` is zero or negative.
        """
        validate_chunk_size(chunk_size)
        validate_span(offset, length)
        stream = self._inner.read_range(
            path, offset=offset, length=length, chunk_size=chunk_size
        )
        if self._sink is not None:
            stream = self._count('read', path, stream, self._sink, offset)
        yield from stream

    def write_stream(
        self,
        path: PurePosixPath,
        data: Iterator[bytes],
        *,
        chunk_size: int | None = None,
        mode: EchoMode,
        content_type: str | None,
        metadata: Mapping[str, str] | None = None,
    ) -> None:
        """Write a chunk stream, emitting an event per pulled chunk.

        Raises:
            ValueError: If ``chunk_size`` is zero or negative.
        """
        validate_chunk_size(chunk_size)
        if self._sink is not None:
            data = self._count('write', path, data, self._sink)
        self._inner.write_stream(
            path,
            data,
            chunk_size=chunk_size,
            mode=mode,
            content_type=content_type,
            metadata=metadata,
        )
