#!/usr/bin/env python3
"""Generate the sync tree from the async source of truth.

Token-level unasync: reads ``src/storix/_async`` and ``tests/_async``,
emits ``src/storix/_sync`` and ``tests/_sync``. Whitelist-driven: any
async-only construct without a registered translation aborts generation
with file:line diagnostics instead of emitting silently-wrong sync code.

Usage:
    uv run python scripts/unasync.py           # (re)generate
    uv run python scripts/unasync.py --check   # regenerate, fail on drift
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys

from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent

MAPPINGS: tuple[tuple[Path, Path], ...] = (
    (ROOT / 'src' / 'storix' / '_async', ROOT / 'src' / 'storix' / '_sync'),
    (ROOT / 'tests' / '_async', ROOT / 'tests' / '_sync'),
)

# Hand-written twin pairs. _compat/test_compat: the audited concurrency
# exception. local.py/azure.py: primitives differ by flavor (aiofiles and
# the .aio SDK vs their sync counterparts). Never generated; the sync
# twin must exist.
SKIP_NAMES = frozenset({'_compat.py', 'test_compat.py', 'local.py', 'azure.py'})

# A line carrying this marker is exempt from the forbidden-token scan.
ALLOW_MARKER = '# codegen: allow'

# Async-only constructs with no registered translation: generation fails
# rather than producing silently-wrong sync code. Concurrency belongs in
# _compat.gather (the skipped, hand-audited twin pair).
FORBIDDEN = tuple(
    re.compile(pattern)
    for pattern in (
        r'\basyncio\b',
        r'\bTaskGroup\b',
        r'\baiofiles\b',
        r'\banyio\b',
        r'\btrio\b',
    )
)

# Ordered token substitutions; longest/most-specific first.
SUBSTITUTIONS = tuple(
    (re.compile(pattern), replacement)
    for pattern, replacement in (
        (r'storix\._async', 'storix._sync'),
        (r'\basync def\b', 'def'),
        (r'\basync for\b', 'for'),
        (r'\basync with\b', 'with'),
        (r'\bawait ', ''),
        (r'\bAsyncIterator\b', 'Iterator'),
        (r'\bAsyncIterable\b', 'Iterable'),
        (r'\bAsyncGenerator\b', 'Generator'),
        (r'\bAsyncDataBuffer\b', 'DataBuffer'),
        (r'\bAbstractAsyncContextManager\b', 'AbstractContextManager'),
        (r'\baiter\(', 'iter('),
        (r'\banext\(', 'next('),
        (r'\b__aenter__\b', '__enter__'),
        (r'\b__aexit__\b', '__exit__'),
        (r'\b__aiter__\b', '__iter__'),
        (r'\b__anext__\b', '__next__'),
        (r'\bStopAsyncIteration\b', 'StopIteration'),
        (r'\basynccontextmanager\b', 'contextmanager'),
        (r'\baclosing\b', 'closing'),
    )
)


def _header(source: Path) -> str:
    rel = source.relative_to(ROOT)
    return (
        f'# DO NOT EDIT - GENERATED by scripts/unasync.py\n# source of truth: {rel}\n'
    )


def _transform(source: Path, text: str) -> tuple[str, list[str]]:
    """Return the sync text and any forbidden-construct diagnostics."""
    errors: list[str] = []
    out: list[str] = []
    for lineno, line in enumerate(text.splitlines(keepends=True), start=1):
        if ALLOW_MARKER not in line:
            errors.extend(
                f'{source.relative_to(ROOT)}:{lineno}: '
                f'untranslatable async construct {pattern.pattern!r}'
                for pattern in FORBIDDEN
                if pattern.search(line)
            )
        rendered = line
        for pattern, replacement in SUBSTITUTIONS:
            rendered = pattern.sub(replacement, rendered)
        out.append(rendered)
    return ''.join(out), errors


def generate() -> int:
    failures: list[str] = []
    for src_root, dst_root in MAPPINGS:
        expected: set[Path] = set()
        for source in sorted(src_root.rglob('*.py')):
            dest = dst_root / source.relative_to(src_root)
            expected.add(dest)

            if source.name in SKIP_NAMES:
                if not dest.exists():
                    failures.append(
                        f'{dest.relative_to(ROOT)}: missing hand-written twin '
                        f'for skipped {source.name}'
                    )
                continue

            sync_text, errors = _transform(source, source.read_text())
            if errors:
                failures.extend(errors)
                continue
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(_header(source) + sync_text)

        # a renamed/deleted async source must not leave a stale sync twin
        if dst_root.exists():
            for leftover in sorted(dst_root.rglob('*.py')):
                if leftover not in expected:
                    leftover.unlink()
                    print(f'removed orphan {leftover.relative_to(ROOT)}')

    if failures:
        print('\n'.join(failures), file=sys.stderr)
        return 1

    # canonicalize output so generated code passes the repo lint/format
    # gates. The unsafe-fix pass is restricted to two rules whose rewrites
    # are provably safe for the patterns the transform produces:
    # C416 ([x for x in it] -> list(it)) and UP028 (yield loop -> yield from).
    targets = [str(dst) for _, dst in MAPPINGS if dst.exists()]
    unsafe_rules = 'C416,UP028'
    # invoke ruff via the current interpreter, not a bare ``ruff`` on PATH:
    # under some launchers (e.g. `just`) PATH may miss it, and check=False
    # would then silently skip the fix pass, leaving un-canonicalized output.
    ruff = [sys.executable, '-m', 'ruff']
    subprocess.run(
        [*ruff, 'check', '--fix', '--unsafe-fixes', '--select', unsafe_rules,
         '--quiet', *targets],
        check=False,
    )  # fmt: skip
    subprocess.run([*ruff, 'check', '--fix', '--quiet', *targets], check=False)
    subprocess.run([*ruff, 'format', '--quiet', *targets], check=True)
    return 0


def check() -> int:
    status = generate()
    if status:
        return status
    targets = [str(dst) for _, dst in MAPPINGS]
    drift = subprocess.run(
        ['git', 'status', '--porcelain', '--', *targets],
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    if drift:
        print('sync tree is out of date; run: uv run python scripts/unasync.py')
        print(drift)
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        '--check',
        action='store_true',
        help='regenerate and fail if the committed sync tree drifted',
    )
    args = parser.parse_args()
    return check() if args.check else generate()


if __name__ == '__main__':
    raise SystemExit(main())
