# DO NOT EDIT - GENERATED by scripts/unasync.py
# source of truth: src/storix/_async/backends/azblob.py
# ruff: noqa: A004 - storix error classes intentionally shadow stdlib names
"""Azure Blob Storage backend (flat namespace).

A typed facade: explicit, documented parameters over the internal
opendal engine, which supplies every port method. Flavor-neutral, so
the sync twin is generated.

The companion to ``AzureBackend``: that one speaks the Data Lake Gen2
endpoint and requires hierarchical namespaces; this one speaks the
plain blob endpoint and works on every storage account, flat
(portal-default) accounts included.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from storix.enums import PathKind
from storix.errors import IsADirectoryError


try:
    from .opendal import OpendalBackend
except ImportError:  # pragma: no cover
    _msg = (
        'azure blob support is not installed. Install it by running '
        "`uv add 'storix[azure]'` (or the lean, blob-only `storix[azblob]`)."
    )
    raise ImportError(_msg) from None

try:
    import azure.storage.blob  # noqa: F401

    _HAS_BLOB_SDK = True
except ImportError:  # pragma: no cover
    _HAS_BLOB_SDK = False


if TYPE_CHECKING:
    from pathlib import PurePosixPath


class AzureBlobBackend(OpendalBackend):
    """Azure Blob Storage, anchored at one container.

    The container anchors the session: port path ``/x`` maps to blob
    name ``x`` (under ``root`` when one is set). Works on any storage
    account; for accounts with hierarchical namespaces enabled,
    ``AzureBackend`` offers richer semantics (atomic renames, true
    appends) over the Data Lake endpoint.

    Advertises the ``custom_metadata`` and ``content_type``
    capabilities always, and ``presigned_urls`` when the credential can
    sign one: a SAS token (opendal appends it) or, with the blob SDK
    installed, an account key (a read SAS is signed locally, 1:1 with
    ``AzureBackend``). Construction is configuration-only; credentials
    are validated on first I/O.
    """

    def __init__(
        self,
        container: str,
        *,
        account_name: str,
        credential: str | None = None,
        endpoint: str | None = None,
        root: str = '/',
    ) -> None:
        """Create an Azure Blob Storage backend.

        Args:
            container: Container anchoring port path ``/``.
            account_name: Azure Storage account name.
            credential: SAS token or account key, distinguished by the
                ``sig=`` marker every SAS token carries (base64 account
                keys cannot contain it). ``None`` means anonymous
                access, for public containers.
            endpoint: Custom blob endpoint URL (emulators, sovereign
                clouds); defaults to the account's public
                ``blob.core.windows.net`` endpoint.
            root: Blob-name prefix anchoring the session's ``/`` inside
                the container, like ``LocalBackend``'s base directory.

        Raises:
            ConfigurationError: If the configuration is rejected.
        """
        options = {
            'endpoint': endpoint or f'https://{account_name}.blob.core.windows.net',
            'root': root,
        }
        if credential is not None:
            kind = 'sas_token' if 'sig=' in credential else 'account_key'
            options[kind] = credential
        super().__init__(
            'azblob',
            container=container,
            account_name=account_name,
            **options,
        )
        # opendal reports presign_read False for an account key, but the blob
        # SDK signs one locally (see make_url), so advertise it honestly.
        if 'account_key' in self._options and _HAS_BLOB_SDK:
            import dataclasses

            self.capabilities = dataclasses.replace(
                self.capabilities, presigned_urls=True
            )

    def locate(self, path: PurePosixPath) -> str:
        """``wasbs://`` URI (the standard blob locator), root included."""
        container = self._options['container']
        account = self._options['account_name']
        prefix = self._options.get('root', '/').rstrip('/')
        return f'wasbs://{container}@{account}.blob.core.windows.net{prefix}{path}'

    def make_url(self, path: PurePosixPath, *, expires_in: int | None = None) -> str:
        """Mint a read-only SAS URL for a blob.

        With an account-key credential the SAS is signed locally (HMAC,
        no request), mirroring ``AzureBackend``; with a SAS-token
        credential opendal's native presign is used instead. The
        configured ``endpoint`` and ``root`` are honored, so Azurite and
        sovereign clouds work and the URL points at the exact object the
        backend reads and writes.

        Args:
            path: Port path of the blob to sign.
            expires_in: URL lifetime in seconds; ``None`` applies the
                storix default lifetime.

        Raises:
            IsADirectoryError: If ``path`` is a directory.
        """
        if 'account_key' not in self._options:
            return super().make_url(path, expires_in=expires_in)

        if expires_in is None:
            from storix.constants import DEFAULT_URL_EXPIRY_SECONDS

            expires_in = DEFAULT_URL_EXPIRY_SECONDS
        raw = self.stat(path)
        if raw.kind is PathKind.DIRECTORY:
            raise IsADirectoryError(path)

        import datetime as dt
        import posixpath

        from azure.storage.blob import BlobSasPermissions, generate_blob_sas

        from storix.utils import craft_blob_url_sas
        from storix.utils.time import utcnow

        blob_name = posixpath.join(
            self._options.get('root', '/'), self._key(path)
        ).lstrip('/')
        token = generate_blob_sas(
            account_name=self._options['account_name'],
            container_name=self._options['container'],
            blob_name=blob_name,
            account_key=self._options['account_key'],
            permission=BlobSasPermissions(read=True),
            expiry=utcnow() + dt.timedelta(seconds=expires_in),
        )
        return craft_blob_url_sas(
            endpoint=self._options['endpoint'],
            container=self._options['container'],
            blob_name=blob_name,
            sas_token=token,
        )
