# DO NOT EDIT - GENERATED by scripts/unasync.py
# source of truth: src/storix/_async/backends/base.py
from __future__ import annotations

import abc

from typing import TYPE_CHECKING

from storix.models import Capabilities

from . import generic


if TYPE_CHECKING:
    from collections.abc import Iterator
    from pathlib import PurePosixPath

    from storix.models import Entry, RawStat
    from storix.types import EchoMode


class BackendBase(abc.ABC):
    """Convenience base pre-wiring the ``generic`` fallbacks.

    Subclasses implement the six abstract primitives and get the rest of
    the :class:`~storix._sync.backends.StorageBackend` contract for free;
    backends with native fast paths override the concrete methods.
    Deliberately does *not* inherit the Protocol - structural typing checks
    conformance, and the core types against the Protocol only. See the
    Protocol docstrings for the semantics each method must honor.
    """

    capabilities: Capabilities = Capabilities()

    @abc.abstractmethod
    def read_stream(self, path: PurePosixPath) -> Iterator[bytes]:
        """Stream a file's contents in chunks."""

    @abc.abstractmethod
    def write(
        self,
        path: PurePosixPath,
        data: Iterator[bytes],
        *,
        mode: EchoMode,
        content_type: str | None,
    ) -> None:
        """Write a file from a chunk stream ('w' truncates, 'a' appends)."""

    @abc.abstractmethod
    def delete(self, path: PurePosixPath) -> None:
        """Delete a leaf: a file or an empty directory."""

    @abc.abstractmethod
    def list_dir(self, path: PurePosixPath) -> Iterator[Entry]:
        """Yield the direct children of a directory."""

    @abc.abstractmethod
    def stat(self, path: PurePosixPath) -> RawStat:
        """Return raw facts about a path (kind, size, timestamps)."""

    @abc.abstractmethod
    def make_dir(self, path: PurePosixPath, *, parents: bool) -> None:
        """Create a directory (``parents=True`` behaves like mkdir -p)."""

    def read(self, path: PurePosixPath) -> bytes:
        """Return the full contents of a file."""
        return generic.read(self, path)

    def move(self, src: PurePosixPath, dst: PurePosixPath) -> None:
        """Move a single file (generic fallback: copy then delete)."""
        generic.move(self, src, dst)

    def copy(self, src: PurePosixPath, dst: PurePosixPath) -> None:
        """Copy a single file (generic fallback: stream read into write)."""
        generic.copy(self, src, dst)

    def delete_tree(self, path: PurePosixPath) -> None:
        """Delete ``path`` and everything below it (rmtree semantics)."""
        generic.delete_tree(self, path)

    def du(self, path: PurePosixPath) -> int:
        """Total size in bytes of the tree rooted at ``path``."""
        return generic.du(self, path)

    def exists(self, path: PurePosixPath) -> bool:
        """Whether anything lives at ``path``."""
        return generic.exists(self, path)
