# DO NOT EDIT - GENERATED by scripts/unasync.py
# source of truth: src/storix/_async/backends/generic.py
"""Generic fallback implementations for the native-fast-path port operations.

Free functions taking the backend as first argument, so backends that do
not subclass :class:`~storix._sync.backends.BackendBase` can still
delegate: ``generic.move(self, src, dst)``. They speak only through
the port's primitives and rely on its error contract (storix errors only).
"""

from __future__ import annotations

from functools import partial
from itertools import chain
from typing import TYPE_CHECKING

from storix._sync._compat import concurrent
from storix._sync._stream import collect, ensure_chunks
from storix.enums import PathKind
from storix.errors import PathNotFoundError


if TYPE_CHECKING:
    from collections.abc import Mapping
    from pathlib import PurePosixPath

    from storix.types import EchoMode

    from ._proto import StorageBackend


def read(backend: StorageBackend, path: PurePosixPath) -> bytes:
    """Collect ``read_stream`` into the full file contents."""
    return collect(backend.read_stream(path))


def write(
    backend: StorageBackend,
    path: PurePosixPath,
    data: bytes,
    *,
    mode: EchoMode,
    content_type: str | None,
    metadata: Mapping[str, str] | None = None,
) -> None:
    """Wrap complete contents as a one-item stream for ``write_stream``."""
    backend.write_stream(
        path,
        ensure_chunks(data),
        mode=mode,
        content_type=content_type,
        metadata=metadata,
    )


def move(backend: StorageBackend, src: PurePosixPath, dst: PurePosixPath) -> None:
    """Move a file or a directory tree as copy-then-delete."""
    props = backend.stat(src)
    if props.kind is PathKind.DIRECTORY:
        copy_tree(backend, src, dst)
        backend.delete_tree(src)
        return
    backend.copy(src, dst)
    backend.delete(src)


def copy(backend: StorageBackend, src: PurePosixPath, dst: PurePosixPath) -> None:
    """Copy a single file by streaming its chunks into a truncating write."""
    data = backend.read_stream(src)
    backend.write_stream(dst, data, mode='w', content_type=None)


def copy_tree(backend: StorageBackend, src: PurePosixPath, dst: PurePosixPath) -> None:
    """Recursively copy a directory tree, fanning out per level.

    Merge-friendly: existing destination directories are reused
    (``mkdir -p`` semantics), so copying into a populated tree overlays
    rather than fails; an existing *file* at a directory's destination
    still raises ``AlreadyExistsError``.
    """
    backend.make_dir(dst, parents=True)

    files: list[str] = []
    subdirs: list[str] = []
    for entry in backend.list_dir(src):
        (subdirs if entry.is_dir else files).append(entry.name)

    concurrent(
        chain(
            (
                partial(copy_tree, backend, src / subdir, dst / subdir)
                for subdir in subdirs
            ),
            (partial(backend.copy, src / file, dst / file) for file in files),
        )
    )


def delete_tree(backend: StorageBackend, path: PurePosixPath) -> None:
    """Delete ``path`` and everything below it, children first.

    Siblings are deleted concurrently (bounded per tree level by the
    ``concurrent`` helper); the directory itself goes last, once empty.
    """
    files: list[PurePosixPath] = []
    subdirs: list[PurePosixPath] = []
    for entry in backend.list_dir(path):
        (subdirs if entry.is_dir else files).append(path / entry.name)

    concurrent(
        chain(
            (partial(backend.delete_tree, subdir) for subdir in subdirs),
            (partial(backend.delete, file) for file in files),
        )
    )
    backend.delete(path)


def du(backend: StorageBackend, path: PurePosixPath) -> int:
    """Sum the sizes of the tree rooted at ``path``.

    Uses listing-provided sizes when available, falling back to per-file
    ``stat`` calls; stats and subtree walks fan out concurrently (bounded
    per tree level by the ``concurrent`` helper).
    """
    props = backend.stat(path)
    if props.kind is PathKind.FILE:
        return props.size

    size = 0
    stat_targets: list[PurePosixPath] = []
    subdirs: list[PurePosixPath] = []
    for entry in backend.list_dir(path):
        child = path / entry.name
        if entry.is_dir:
            subdirs.append(child)
        elif entry.size is not None:
            size += entry.size
        else:
            stat_targets.append(child)

    stats = concurrent(partial(backend.stat, target) for target in stat_targets)
    subtotals = concurrent(partial(backend.du, subdir) for subdir in subdirs)
    return size + sum(s.size for s in stats) + sum(subtotals)


def exists(backend: StorageBackend, path: PurePosixPath) -> bool:
    """Derive existence from ``stat`` and the port's error contract."""
    try:
        backend.stat(path)
    except PathNotFoundError:
        return False
    return True
