# DO NOT EDIT - GENERATED by scripts/unasync.py
# source of truth: src/storix/_async/backends/generic.py
"""Generic fallback implementations for the native-fast-path port operations.

Free functions taking the backend as first argument, so backends that do
not subclass :class:`~storix._sync.backends.BackendBase` can still
delegate: ``generic.move(self, src, dst)``. They speak only through
the port's primitives and rely on its error contract (storix errors only).
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from storix._sync._compat import gather
from storix._sync._stream import collect
from storix.enums import PathKind
from storix.errors import PathNotFoundError


if TYPE_CHECKING:
    from pathlib import PurePosixPath

    from ._proto import StorageBackend


def read(backend: StorageBackend, path: PurePosixPath) -> bytes:
    """Collect ``read_stream`` into the full file contents."""
    return collect(backend.read_stream(path))


def move(backend: StorageBackend, src: PurePosixPath, dst: PurePosixPath) -> None:
    """Move a single file as copy-then-delete."""
    backend.copy(src, dst)
    backend.delete(src)


def copy(backend: StorageBackend, src: PurePosixPath, dst: PurePosixPath) -> None:
    """Copy a single file by streaming its chunks into a truncating write."""
    data = backend.read_stream(src)
    backend.write(dst, data, mode='w', content_type=None)


def delete_tree(backend: StorageBackend, path: PurePosixPath) -> None:
    """Delete ``path`` and everything below it, children first.

    Siblings are deleted concurrently (bounded per tree level by the
    ``gather`` shim); the directory itself goes last, once empty.
    """
    files: list[PurePosixPath] = []
    subdirs: list[PurePosixPath] = []
    for entry in backend.list_dir(path):
        (subdirs if entry.is_dir else files).append(path / entry.name)

    gather(
        *(backend.delete_tree(subdir) for subdir in subdirs),
        *(backend.delete(file) for file in files),
    )
    backend.delete(path)


def du(backend: StorageBackend, path: PurePosixPath) -> int:
    """Sum the sizes of the tree rooted at ``path``.

    Uses listing-provided sizes when available, falling back to per-file
    ``stat`` calls; stats and subtree walks fan out concurrently (bounded
    per tree level by the ``gather`` shim).
    """
    props = backend.stat(path)
    if props.kind is PathKind.FILE:
        return props.size

    size = 0
    stat_targets: list[PurePosixPath] = []
    subdirs: list[PurePosixPath] = []
    for entry in backend.list_dir(path):
        child = path / entry.name
        if entry.is_dir:
            subdirs.append(child)
        elif entry.size is not None:
            size += entry.size
        else:
            stat_targets.append(child)

    stats = gather(*(backend.stat(target) for target in stat_targets))
    subtotals = gather(*(backend.du(subdir) for subdir in subdirs))
    return size + sum(s.size for s in stats) + sum(subtotals)


def exists(backend: StorageBackend, path: PurePosixPath) -> bool:
    """Derive existence from ``stat`` and the port's error contract."""
    try:
        backend.stat(path)
    except PathNotFoundError:
        return False
    return True
